"""PROBE: animals but fertilizer never collected

Generated by tools/make_probes.py from agents/probe.py -- do not edit directly.
Overrides: CROP=None, ANIMAL="COW", COLLECT_FERT=False
"""
"""Single-strategy probe agent for Kaggriculture.

Deliberately *not* a good agent. Each probe commits to one mechanic and runs it
to the exclusion of everything else, so the league can price that mechanic in
isolation: what is a quadrant worth? a farm hand? metered selling? cows versus
melons?

Everything is driven by the tunable block below. `tools/make_probes.py` stamps
out the named probes in `agents/probes/` by rewriting exactly those lines, so
this file stays the single source of truth.

The logic is intentionally simpler than agents/baseline_v1.py: a flat priority
queue, nearest capable unit wins, no zoning and no crop rotation. A probe should
be legible enough that when it scores oddly you can tell why.
"""

import math

# --------------------------------------------------------------------------
# Probe configuration -- rewritten by tools/make_probes.py
# --------------------------------------------------------------------------

CROP = None    # crop to plant everywhere, or None to farm no crops
ANIMAL = "COW"    # animal to raise everywhere, or None to keep none
MAX_QUADRANTS = 3         # 1..4
HAND_CAP = 12             # 0 disables hiring entirely
HIRE_BUDGET_FRAC = 0.06   # share of cash a day's payroll may consume
SELL_MODE = "metered"     # "metered" | "dump" | "hoard"
COLLECT_FERT = False    # collect and sell the free daily fertilizer
HARVEST_PRODUCT = True    # harvest eggs/milk/wool at all
ANIMAL_CAP = 24           # herd ceiling

# --------------------------------------------------------------------------
# Engine constants
# --------------------------------------------------------------------------

CROPS = {
    "WHEAT":      {"seed": 10, "first_yield_day": 2, "max_yield_day": 4, "interval": 0, "max_yield": 6, "ongoing": False},
    "CARROT":     {"seed": 20, "first_yield_day": 2, "max_yield_day": 3, "interval": 0, "max_yield": 4, "ongoing": False},
    "TOMATO":     {"seed": 50, "first_yield_day": 8, "max_yield_day": 8, "interval": 1, "max_yield": 4, "ongoing": True},
    "STRAWBERRY": {"seed": 100, "first_yield_day": 10, "max_yield_day": 10, "interval": 2, "max_yield": 4, "ongoing": True},
    "MELON":      {"seed": 80, "first_yield_day": 10, "max_yield_day": 12, "interval": 0, "max_yield": 6, "ongoing": False},
}

ANIMALS = {
    "GOOSE": {"cost": 300, "structure": "COOP",    "first_yield_day": 4, "interval": 1, "max_held": 4, "product": "EGG"},
    "COW":   {"cost": 400, "structure": "PASTURE", "first_yield_day": 8, "interval": 2, "max_held": 6, "product": "MILK"},
    "SHEEP": {"cost": 500, "structure": "PASTURE", "first_yield_day": 6, "interval": 3, "max_held": 6, "product": "WOOL"},
}

PRODUCTS = ["WHEAT", "CARROT", "TOMATO", "STRAWBERRY", "MELON", "EGG", "MILK", "WOOL", "FERTILIZER"]

MARKET_PARAMS = {
    "WHEAT":      {"base":  25, "I0": 10000, "T": 400, "below_func": "sqrt",   "below_target": 0.80, "above_func": "log",    "above_target": 0.20},
    "CARROT":     {"base":  35, "I0": 10000, "T": 450, "below_func": "log",    "below_target": 0.20, "above_func": "sqrt",   "above_target": 0.70},
    "TOMATO":     {"base":  60, "I0": 10000, "T": 200, "below_func": "linear", "below_target": 0.40, "above_func": "sqrt",   "above_target": 0.60},
    "STRAWBERRY": {"base": 120, "I0": 10000, "T": 100, "below_func": "sqrt",   "below_target": 0.70, "above_func": "linear", "above_target": 1.60},
    "MELON":      {"base": 250, "I0": 10000, "T": 300, "below_func": "log",    "below_target": 0.20, "above_func": "sq",     "above_target": 3.60},
    "EGG":        {"base":  50, "I0": 10000, "T": 332, "below_func": "linear", "below_target": 0.40, "above_func": "log",    "above_target": 0.20},
    "MILK":       {"base": 160, "I0": 10000, "T": 122, "below_func": "sqrt",   "below_target": 0.60, "above_func": "linear", "above_target": 1.60},
    "WOOL":       {"base": 200, "I0": 10000, "T": 105, "below_func": "log",    "below_target": 0.20, "above_func": "sq",     "above_target": 3.20},
    "FERTILIZER": {"base": 100, "I0": 10000, "T": 200, "below_func": "linear", "below_target": 0.40, "above_func": "linear", "above_target": 0.40},
}

LAND_PRICES = [1000, 2000, 4000]
SHED_CAPACITY = 100
MAX_ORDERS = 10
LIQUIDATE_DAY = 28

WATER_MAX = {}
for _c, _d in CROPS.items():
    if not _d["ongoing"]:
        _w = _d["max_yield_day"] - (_d["max_yield_day"] + 1) // 2 + 1
        WATER_MAX[_c] = min(_d["max_yield"], 1 + _w)


def _shape(f, x):
    x = max(0.0, x)
    if f == "linear":
        return x
    if f == "sq":
        return x * x
    if f == "sqrt":
        return math.sqrt(x)
    if f == "log":
        return math.log(1.0 + x)
    if f == "log10":
        return math.log10(1.0 + x)
    return x


def market_price(item, inv):
    p = MARKET_PARAMS[item]
    base, i0, t = p["base"], p["I0"], p["T"]
    if inv < i0:
        amp = p["below_target"] * base / _shape(p["below_func"], t)
        return max(1, int(round(base + amp * _shape(p["below_func"], i0 - inv))))
    amp = p["above_target"] * base / _shape(p["above_func"], t)
    return max(1, int(round(base - amp * _shape(p["above_func"], inv - i0))))


def _fib(n):
    a, b = 1, 1
    for _ in range(n):
        a, b = b, a + b
    return a


def _shed_tiles(n):
    h = n // 2
    return [(h - 1, h - 1), (h, h - 1), (h - 1, h), (h, h)]


def _dist(ax, ay, bx, by):
    return abs(ax - bx) + abs(ay - by)


def _step_toward(fx, fy, tx, ty):
    if fx != tx and abs(fx - tx) >= abs(fy - ty):
        return "EAST" if tx > fx else "WEST"
    if fy != ty:
        return "SOUTH" if ty > fy else "NORTH"
    if fx != tx:
        return "EAST" if tx > fx else "WEST"
    return None


def _plan(obs):
    player = obs.get("player", 0)
    farms = obs.get("farms", []) or []
    if not farms or player >= len(farms):
        return {"farmer": ["PASS"], "hands": [], "market": []}

    farm = farms[player]
    priv = obs.get("private", {}) or {}
    shed = dict(priv.get("shed", {}) or {})
    seeds = dict(priv.get("seeds", {}) or {})
    invs = [dict(d or {}) for d in (priv.get("inventories", []) or [{}])]
    tiles = farm["tiles"]
    n = len(tiles)
    day, hour = obs.get("day", 0), obs.get("hour", 0)
    money = farm["money"]
    m_inv = dict((obs.get("market", {}) or {}).get("inventory", {}) or {})
    unlocked = farm.get("unlocked_quadrants", ["NW"]) or ["NW"]
    endgame = day >= LIQUIDATE_DAY
    shed_total = sum(shed.values())

    units = [(0, farm["farmer"][0], farm["farmer"][1])]
    for i, pos in enumerate(farm.get("hands", []) or []):
        units.append((i + 1, pos[0], pos[1]))
    n_units = len(units)
    while len(invs) < n_units:
        invs.append({})

    st = _shed_tiles(n)
    st_set = set(st)
    struct_kind = ANIMALS[ANIMAL]["structure"] if ANIMAL else None

    animals, empty_structs, plants, weeds, free = [], [], [], [], []
    n_crop = 0
    for y in range(n):
        for x in range(n):
            t = tiles[y][x]
            if t == "LOCKED":
                continue
            if t is None:
                free.append((x, y))
            elif isinstance(t, dict):
                k = t.get("kind")
                if k == "WEED":
                    weeds.append((x, y))
                elif k == "PLANT":
                    plants.append((x, y, t))
                    n_crop += 1
                elif "animal" in t:
                    animals.append((x, y, t))
                elif k == struct_kind:
                    empty_structs.append((x, y))

    n_animals = len(animals)
    carried_animals = sum(iv.get(ANIMAL, 0) for iv in invs[:n_units]) if ANIMAL else 0
    in_shed_animals = shed.get(ANIMAL, 0) if ANIMAL else 0
    waiting = carried_animals + in_shed_animals

    tasks = []
    unfed = 0
    if not endgame:
        for (x, y, t) in animals:
            if not t.get("fed_today"):
                unfed += 1
                tasks.append((0 if t.get("consecutive_unfed", 0) >= 1 else 5, x, y, ["FEED"], "WHEAT"))
            held = t.get("yield_units", 0)
            cap = ANIMALS[t["animal"]]["max_held"]
            if HARVEST_PRODUCT and held >= cap:
                tasks.append((1, x, y, ["HARVEST"], None))
            if COLLECT_FERT and t.get("fertilizer_available"):
                tasks.append((3, x, y, ["COLLECT_FERTILIZER"], None))
            if not t.get("cared_today"):
                tasks.append((6, x, y, ["CARE"], None))
            if HARVEST_PRODUCT and 0 < held >= cap - 2:
                tasks.append((8, x, y, ["HARVEST"], None))

        for (x, y, t) in plants:
            cd = CROPS[t["crop"]]
            age = day - t["planted_day"]
            watered = t.get("watered_today", False)
            yu = t.get("yield_units", 0)
            thirsty = t.get("consecutive_unwatered", 0) >= 1
            if cd["ongoing"]:
                if not watered:
                    tasks.append((2 if thirsty else 7, x, y, ["WATER"], None))
                if age >= cd["first_yield_day"] and yu >= 2:
                    tasks.append((4, x, y, ["HARVEST"], None))
            else:
                tgt = WATER_MAX[t["crop"]]
                if age >= cd["first_yield_day"] and (yu >= tgt or age >= cd["max_yield_day"]):
                    tasks.append((1, x, y, ["HARVEST"], None))
                elif not watered:
                    w0 = (cd["max_yield_day"] + 1) // 2
                    if thirsty:
                        tasks.append((2, x, y, ["WATER"], None))
                    elif w0 <= age <= cd["max_yield_day"] and yu < tgt:
                        tasks.append((4, x, y, ["WATER"], None))

        carried_wheat = sum(iv.get("WHEAT", 0) for iv in invs[:n_units])
        gap = unfed - carried_wheat
        if gap > 0 and shed.get("WHEAT", 0) > 0:
            for _ in range(min(n_units, -(-gap // 8))):
                tasks.append((1, None, None, ["PICKUP_WHEAT"], None))

        if ANIMAL:
            for _ in range(in_shed_animals):
                tasks.append((5, None, None, ["PICKUP_ANIMAL"], None))
            for (x, y) in empty_structs:
                tasks.append((5, x, y, ["PLACE", ANIMAL], ANIMAL))
            need = max(0, min(waiting + 2, ANIMAL_CAP - n_animals) - len(empty_structs))
            build = "BUILD_PASTURE" if struct_kind == "PASTURE" else "BUILD_COOP"
        else:
            need, build = 0, None

        last_day = {"WHEAT": 24, "CARROT": 25, "TOMATO": 19, "STRAWBERRY": 13, "MELON": 18}
        can_plant = seeds.get(CROP, 0) if CROP else 0
        for (x, y) in sorted(free, key=lambda p: min(_dist(p[0], p[1], sx, sy) for sx, sy in st)):
            if need > 0:
                tasks.append((5, x, y, [build], None))
                need -= 1
            elif CROP and can_plant > 0 and day <= last_day[CROP]:
                tasks.append((7, x, y, ["PLANT", CROP], None))
                can_plant -= 1
        for (x, y) in weeds:
            tasks.append((9, x, y, ["DIG"], None))
    else:
        for (x, y, t) in animals:
            if t.get("yield_units", 0) > 0:
                tasks.append((0, x, y, ["HARVEST"], None))
        for (x, y, t) in plants:
            if t.get("yield_units", 0) > 0 and day - t["planted_day"] >= CROPS[t["crop"]]["first_yield_day"]:
                tasks.append((0, x, y, ["HARVEST"], None))

    tasks.sort(key=lambda t: t[0])

    actions = [None] * n_units
    busy = [False] * n_units
    claimed = set()
    wheat_left = shed.get("WHEAT", 0)
    animals_left = in_shed_animals

    for (prio, tx, ty, act, need_item) in tasks:
        op = act[0]
        if tx is None:
            best, bd, bt = None, None, None
            for k, (idx, ux, uy) in enumerate(units):
                if busy[k]:
                    continue
                if op == "PICKUP_WHEAT" and invs[idx].get("WHEAT", 0) >= 4:
                    continue
                if op == "PICKUP_ANIMAL" and ANIMAL and invs[idx].get(ANIMAL, 0):
                    continue
                tgt = min(st, key=lambda p: _dist(ux, uy, p[0], p[1]))
                d = _dist(ux, uy, tgt[0], tgt[1])
                if bd is None or d < bd:
                    best, bd, bt = k, d, tgt
            if best is None:
                continue
            idx, ux, uy = units[best]
            if (ux, uy) in st_set:
                if op == "PICKUP_WHEAT":
                    take = min(8, wheat_left)
                    if take <= 0:
                        continue
                    wheat_left -= take
                    actions[best] = ["PICKUP", "WHEAT", take]
                else:
                    if animals_left <= 0:
                        continue
                    animals_left -= 1
                    actions[best] = ["PICKUP", ANIMAL, 1]
            else:
                actions[best] = [_step_toward(ux, uy, bt[0], bt[1])]
            busy[best] = True
            continue

        if (tx, ty, op) in claimed:
            continue
        best, bd = None, None
        for k, (idx, ux, uy) in enumerate(units):
            if busy[k] or (need_item and invs[idx].get(need_item, 0) <= 0):
                continue
            d = _dist(ux, uy, tx, ty)
            if bd is None or d < bd:
                best, bd = k, d
        if best is None:
            continue
        idx, ux, uy = units[best]
        actions[best] = act if (ux, uy) == (tx, ty) else [_step_toward(ux, uy, tx, ty)]
        busy[best] = True
        claimed.add((tx, ty, op))

    for k, (idx, ux, uy) in enumerate(units):
        if busy[k]:
            continue
        inv = invs[idx]
        produce = sum(v for it, v in inv.items() if it in PRODUCTS and it != "WHEAT")
        if (ux, uy) in st_set:
            if produce > 0 and shed_total < SHED_CAPACITY:
                actions[k] = ["DROP"]
            elif not endgame and n_animals and wheat_left > 0 and inv.get("WHEAT", 0) < 2:
                take = min(8, wheat_left)
                wheat_left -= take
                actions[k] = ["PICKUP", "WHEAT", take]
            else:
                actions[k] = ["PASS"]
        elif produce >= 6 or endgame or sum(inv.values()) >= 12:
            tgt = min(st, key=lambda p: _dist(ux, uy, p[0], p[1]))
            mv = _step_toward(ux, uy, tgt[0], tgt[1])
            actions[k] = [mv] if mv else ["PASS"]
        else:
            actions[k] = ["PASS"]
        busy[k] = True

    # ---------------- market ----------------
    orders = []
    spend = 0.0

    def afford(c):
        return money - spend >= c

    if not endgame:
        if HAND_CAP > 0 and hour <= 3:
            hires = farm.get("hires_today", 0)
            payroll = sum(_fib(i) for i in range(hires))
            budget = max(4.0, money * HIRE_BUDGET_FRAC)
            while len(orders) < 7 and hires < HAND_CAP:
                c = _fib(hires)
                if payroll + c > budget or not afford(c + 40):
                    break
                orders.append(["HIRE"])
                spend += c
                payroll += c
                hires += 1

        n_extra = len(unlocked) - 1
        if n_extra < min(len(LAND_PRICES), MAX_QUADRANTS - 1) and len(orders) < MAX_ORDERS:
            price = LAND_PRICES[n_extra]
            if len(free) <= 8 and afford(price + [600, 1500, 3000][n_extra]):
                orders.append(["BUY_LAND"])
                spend += price

        if (ANIMAL and len(orders) < MAX_ORDERS and day <= 23 and waiting < 2
                and n_animals + waiting < ANIMAL_CAP and shed_total < SHED_CAPACITY - 8):
            c = ANIMALS[ANIMAL]["cost"]
            if afford(c + (100 if day < 12 else 400)):
                orders.append(["BUY_ANIMAL", ANIMAL, 1])
                spend += c

        if CROP and len(orders) < MAX_ORDERS and len(free) > 0:
            have = n_crop + seeds.get(CROP, 0)
            want = min(6, len(free))
            if have < len(free) + n_crop:
                c = CROPS[CROP]["seed"]
                k = max(0, min(want, len(free) - seeds.get(CROP, 0)))
                if k > 0 and afford(c * k + 100):
                    orders.append(["BUY_SEED", CROP, k])
                    spend += c * k

        if n_animals and len(orders) < MAX_ORDERS and shed_total < SHED_CAPACITY - 10:
            need_w = min(28, n_animals * 2)
            if shed.get("WHEAT", 0) < need_w:
                wp = market_price("WHEAT", m_inv.get("WHEAT", 10000) - 1)
                k = min(10, need_w - shed.get("WHEAT", 0))
                if afford(wp * k + 150):
                    orders.append(["BUY_PRODUCT", "WHEAT", k])
                    spend += wp * k

    sellable = []
    for item in PRODUCTS:
        held = shed.get(item, 0)
        if held <= 0:
            continue
        if item == "WHEAT" and not endgame and n_animals:
            held = max(0, held - min(28, n_animals * 2))
            if held <= 0:
                continue
        inv0 = m_inv.get(item, 10000)
        sellable.append((market_price(item, inv0) * min(held, 8), item, held, inv0))
    sellable.sort(reverse=True)

    pressure = shed_total >= 74
    for (_, item, held, inv0) in sellable:
        if len(orders) >= MAX_ORDERS:
            break
        if endgame:
            qty = min(held, 40)
        elif SELL_MODE == "hoard":
            qty = min(held, 8) if pressure else 0
        elif SELL_MODE == "dump":
            qty = min(held, 40)
        else:
            floor = MARKET_PARAMS[item]["base"] * (0.0 if item == "FERTILIZER" else 0.55)
            qty = 0
            lim = min(8, held)
            while qty < lim and market_price(item, inv0 + qty) >= floor:
                qty += 1
            if pressure and qty == 0:
                qty = min(held, 8)
        if qty > 0:
            orders.append(["SELL", item, qty])

    return {
        "farmer": actions[0] if actions and actions[0] else ["PASS"],
        "hands": [a if a else ["PASS"] for a in actions[1:]],
        "market": orders[:MAX_ORDERS],
    }


def agent(obs):
    try:
        return _plan(obs)
    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
