#!/usr/bin/env python
"""Export a trained checkpoint as a torch-free, self-contained agent directory.

    python rl/export_agent.py --ckpt rl/runs/m1/latest.pt --name groundhog

Produces rl/out/<name>/ holding main.py (numpy forward, greedy argmax),
weights.npz, and private copies of obs.py / actions.py / kg_rules.py so the
directory works anywhere the loader puts it on sys.path -- locally under
tools/eval.py and unpacked flat in /kaggle_simulations/agent/ alike.

Verifies the way CLAUDE.md demands: emulates get_last_callable on the written
file and asks the loaded function for an answer on a real reset observation.
"""

import argparse
import os
import shutil
import sys

_RL = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_RL)
sys.path.insert(0, _RL)

MAIN_TEMPLATE = '''"""RL policy agent: numpy MLP forward over masked heads.
Inference mode is baked at export: greedy argmax (default) or softmax
sampling (--sample T) -- measured on this line's checkpoints, sampling is
worth 10-30pp against recording-lineage opponents (argmax mode collapse)
and costs ~10k margin against reactive ones; pick per destination.
Generated by rl/export_agent.py -- do not hand-edit; retrain and re-export.

No __file__ here: get_last_callable execs this source with empty globals and
only *appends* the agent directory to sys.path. Sibling modules carry names
unique to THIS export ({sfx}): unique vs other repo agents because of the
kg_rl_ prefix, and unique vs our *own* other exports because two of them in
one process would otherwise share sys.modules entries -- the second agent
would silently read the first one's weights via the cached module __file__
(observed: two different checkpoints playing byte-identical episodes).
"""

import os

import numpy as np

import kg_rl_obs_{sfx} as _O
import kg_rl_actions_{sfx} as _A

_W = dict(np.load(os.path.join(
    os.path.dirname(os.path.abspath(_O.__file__)), "weights.npz")))


def _trunk_extra(h):
    # Residual blocks (--depth > 2). Zero-init second matrix at birth, so an
    # npz without them is a depth-2 net and this loop is a no-op.
    i = 0
    while f"e{i}aw" in _W:
        a = np.maximum(0.0, _W[f"e{i}aw"] @ h + _W[f"e{i}ab"])
        h = h + _W[f"e{i}bw"] @ a + _W[f"e{i}bb"]
        i += 1
    return h


def _forward(x):
    h = np.maximum(0.0, _W["l1w"] @ x + _W["l1b"])
    h = np.maximum(0.0, _W["l2w"] @ h + _W["l2b"])
    h = _trunk_extra(h)
    f, m = _W["fw"] @ h + _W["fb"], _W["mw"] @ h + _W["mb"]
    hl = _W["hw"] @ h + _W["hb"] if "hw" in _W else None
    if "d_l1w" in _W:  # residual export: frozen prior + learned correction
        h = np.maximum(0.0, _W["d_l1w"] @ x + _W["d_l1b"])
        h = np.maximum(0.0, _W["d_l2w"] @ h + _W["d_l2b"])
        f = f + _W["d_fw"] @ h + _W["d_fb"]
        m = m + _W["d_mw"] @ h + _W["d_mb"]
        if "d_hw" in _W:  # multi-head hands live on the delta trunk
            hl = _W["d_hw"] @ h + _W["d_hb"]
    return f, m, hl


_TEMP = {temp}   # 0 = greedy argmax; >0 = softmax sampling at this temperature
_RNG = np.random.default_rng(20260820)
_SHEEP_CASH_MAX = {sheep_cash_max}
_SHEEP_MIN_DAY = {sheep_min_day}
_SHEEP_TIMEOUT = {sheep_timeout}
_SHEEP_LAST_STEP = -1
_SHEEP_DECIDED = False
_SHEEP_ACTIVE = False
_SHEEP_TRIGGER_STEP = -1
_SHEEP_START = 0


def _pick(logits):
    if _TEMP <= 0.0:
        return int(logits.argmax())
    z = (logits - logits.max()) / _TEMP
    p = np.exp(z)
    p /= p.sum()
    return int(_RNG.choice(len(p), p=p))


def _count_sheep(farm):
    return sum(
        1 for row in (farm.get("tiles") or []) for tile in (row or [])
        if isinstance(tile, dict) and tile.get("animal") == "SHEEP"
    )


def _sheep_option(obs, action):
    """One-shot FOLLOW_POLICY/BUY_ONE_SHEEP controller; disabled at cash 0."""
    global _SHEEP_LAST_STEP, _SHEEP_DECIDED, _SHEEP_ACTIVE
    global _SHEEP_TRIGGER_STEP, _SHEEP_START
    if _SHEEP_CASH_MAX <= 0:
        return action
    try:
        step = int(obs.get("step", 0) or 0)
        if step == 0 or step <= _SHEEP_LAST_STEP:
            _SHEEP_DECIDED = False
            _SHEEP_ACTIVE = False
            _SHEEP_TRIGGER_STEP = -1
            _SHEEP_START = 0
        _SHEEP_LAST_STEP = step

        player = int(obs.get("player", 0) or 0)
        farm = (obs.get("farms") or [])[player]
        private = obs.get("private") or {}
        shed = private.get("shed") or {}
        money = float(farm.get("money", 0) or 0)
        sheep = _count_sheep(farm)
        room = sum(int(v or 0) for v in shed.values()) < 100

        if (not _SHEEP_DECIDED and step // 24 >= _SHEEP_MIN_DAY
                and money >= 1500 and room):
            _SHEEP_DECIDED = True
            _SHEEP_ACTIVE = money <= _SHEEP_CASH_MAX
            _SHEEP_TRIGGER_STEP = step
            _SHEEP_START = sheep

        if not _SHEEP_ACTIVE:
            return action
        if sheep > _SHEEP_START or step - _SHEEP_TRIGGER_STEP >= _SHEEP_TIMEOUT:
            _SHEEP_ACTIVE = False
            return action

        inventories = private.get("inventories") or []
        carried = sum(int(inv.get("SHEEP", 0) or 0) for inv in inventories)
        unplaced = int(shed.get("SHEEP", 0) or 0) + carried
        out = dict(action)
        if unplaced <= 0 and money >= 1500 and room:
            out["market"] = [["BUY_ANIMAL", "SHEEP", 1]]

        scan = _A._scan(obs)
        if unplaced > 0 and scan["pasture_free"]:
            farmer = _A._farmer_action(obs, "PLACE_SHEEP", scan)
        elif scan["empty"]:
            farmer = _A._farmer_action(obs, "BUILD_PASTURE", scan)
        else:
            farmer = None
        if farmer:
            out["farmer"] = farmer
        return out
    except Exception:
        return action


def _act(obs_dict):
    x = _O.encode(obs_dict)
    flog, mlog, hlog = _forward(x)
    flog[~_A.farmer_mask(obs_dict)] = -1e9
    mlog[~_A.market_mask(obs_dict)] = -1e9
    if hlog is None:
        return _sheep_option(
            obs_dict, _A.decode(obs_dict, _pick(flog), _pick(mlog)))
    hm = np.array(_A.hand_task_mask(obs_dict), dtype=bool)
    hlog = hlog.reshape(hm.shape)
    hlog[~hm] = -1e9
    fa = _pick(flog)
    tasks = [_pick(row) for row in hlog]
    if "cfw" in _W:
        # Coupled export (CoupledMultiHeadMasked): the market head is
        # conditioned on THIS turn's farmer action and hand tasks. Skipping
        # this would silently play the uncoupled base policy -- the
        # loads-the-unwrapped-agent failure mode, one layer down.
        mlog = mlog + _W["cfw"][:, fa] + _W["chw"][:, tasks].mean(axis=1)
        mlog[~_A.market_mask(obs_dict)] = -1e9
    if "msb" in _W:
        # Multi-order head (MultiOrderMultiHead): K market slots, slot k
        # conditioned on slot k-1's action. Emitting slot 0 alone would be a
        # different agent -- and one that looks fine, because a one-order
        # policy still banks money. Orders are concatenated in slot order and
        # capped at MAX_ORDERS; the engine drops extras silently.
        mask = _A.market_mask(obs_dict)
        out = None
        prev = None
        for k in range(_W["msb"].shape[0]):
            lk = mlog + _W["msb"][k]
            if prev is not None:
                lk = lk + _W["cmw"][:, prev]
            lk[~mask] = -1e9
            a = _pick(lk)
            d = _A.decode_multi(obs_dict, fa, tasks, a)
            if out is None:
                out = d                       # slot 0: the FULL decode
            else:
                # Slots 1.. contribute exactly ONE order each, which is what
                # the training decode does (engine_t_idx puts each extra macro
                # in one free slot through a bare LUT). Running the full
                # decode here instead made training and deployment disagree:
                # [NOOP, HIRE] was 1 order in training and 10 deployed, and
                # [NOOP, SELL_MELON] on the liquidation day was 1 against 3.
                out["market"] = (out["market"] + d["market"][:1])[:10]
            prev = a
        return _sheep_option(obs_dict, out)
    return _sheep_option(
        obs_dict, _A.decode_multi(obs_dict, fa, tasks, _pick(mlog)))


def agent(obs, config=None):
    try:
        return _act(obs)
    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
'''


def get_last_callable(path):
    """Faithful emulation of kaggle_environments.agent.get_last_callable:
    empty globals (no __file__), agent dir *appended* to sys.path."""
    with open(path) as f:
        code = compile(f.read(), path, "exec")
    env = {}
    sys.path.append(os.path.dirname(path))
    try:
        exec(code, env)
    finally:
        sys.path.pop()
    callables = [v for v in env.values() if callable(v)]
    return callables[-1] if callables else None


def write_agent_dir(policy, out_dir, temperature=0.0, sheep_cash_max=0,
                    sheep_min_day=4, sheep_timeout=96):
    """Write a ready-to-run numpy agent directory for `policy` and verify the
    loader contract statically. Shared by the CLI export and league promotion.

    Module names are suffixed with this export's identity: kg_rules is the
    shared rules mirror (collisions are harmless by design), but obs/actions
    must be unique per export or two of our agents in one process share the
    cached module and the second reads the first's weights."""
    import re
    if sheep_cash_max < 0:
        raise ValueError("sheep_cash_max must be non-negative")
    if sheep_min_day < 0:
        raise ValueError("sheep_min_day must be non-negative")
    if sheep_timeout <= 0:
        raise ValueError("sheep_timeout must be positive")
    os.makedirs(out_dir, exist_ok=True)
    sfx = re.sub(r"\W", "_", os.path.basename(os.path.normpath(out_dir)))
    policy.export_npz(os.path.join(out_dir, "weights.npz"))
    for src, dst in ((os.path.join(_RL, "obs.py"), f"kg_rl_obs_{sfx}.py"),
                     (os.path.join(_RL, "actions.py"), f"kg_rl_actions_{sfx}.py"),
                     (os.path.join(_REPO, "agents", "kg_rules.py"), "kg_rules.py")):
        shutil.copy(src, os.path.join(out_dir, dst))
    main_path = os.path.join(out_dir, "main.py")
    with open(main_path, "w") as f:
        f.write(MAIN_TEMPLATE.replace("{sfx}", sfx)
                .replace("{temp}", repr(float(temperature)))
                .replace("{sheep_cash_max}", repr(int(sheep_cash_max)))
                .replace("{sheep_min_day}", repr(int(sheep_min_day)))
                .replace("{sheep_timeout}", repr(int(sheep_timeout))))
    fn = get_last_callable(main_path)
    assert fn is not None and fn.__name__ == "agent", \
        f"last callable is {fn}, expected the agent"
    return main_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--out", default=os.path.join(_RL, "out"))
    ap.add_argument("--sample", type=float, default=0.0,
                    help="softmax sampling temperature baked into the "
                         "export (0 = greedy argmax)")
    ap.add_argument("--sheep-cash-max", type=int, default=0,
                    help="enable the one-sheep option at or below this cash")
    ap.add_argument("--sheep-min-day", type=int, default=4)
    ap.add_argument("--sheep-timeout", type=int, default=96)
    args = ap.parse_args()

    import torch
    from policy import Policy
    import actions as A
    import obs as O

    out_dir = os.path.join(args.out, args.name)

    ck = torch.load(args.ckpt, map_location="cpu", weights_only=False)
    sd = ck["model"]

    # A checkpoint trained with --fixed-farm-tape must NOT be exported down
    # this path. Under that flag the farm program (farmer + every hand slot)
    # and the tape's non-SELL market orders are grafted on at the raw-op
    # level, so only SELL received an objective -- and MarketOnlyMultiHead is
    # a parameterless distribution subclass, so the state dict is
    # SHAPE-INDISTINGUISHABLE from a plain --multi-head run. `_act` below
    # would hand farmer, all twelve hand slots and the full 31-way market
    # mask straight back to heads that were never trained, with no tape and
    # no buys-first merge.
    #
    # That is exactly how 8db606f's --fixed-market-profile arm turned out
    # undeliverable: "export_agent.py then hands market decisions straight
    # back to it ... 34,321 against the baseline export's 51,058, a 33%
    # collapse produced purely by the export path rather than by training."
    # Worse here, because the farm heads are not frozen -- they sit on the
    # shared l1/l2 trunk and drift with the market head's gradient, so an
    # ungrafted export is not even the warm start it began from.
    #
    # Nothing downstream would catch it: tests/test_export_agent.py only
    # covers the sheep option, and tools/package.sh asserts money > 3000
    # while the tape alone banks ~186k. So refuse here.
    _ck_args = ck.get("args") or {}
    if _ck_args.get("fixed_farm_tape"):
        raise SystemExit(
            f"refusing to export {args.ckpt}: it was trained with\n"
            f"  --fixed-farm-tape {_ck_args['fixed_farm_tape']}\n"
            f"  --farm-tape-market {_ck_args.get('farm_tape_market')}\n"
            f"so only its market head received an objective. This path would "
            f"hand the farmer and all hand slots back to untrained, drifted "
            f"heads (the 8db606f failure, measured at -33% there). Such a "
            f"checkpoint needs the grafted export -- main.py must embed the "
            f"tape, take farmer/hands/non-SELL market from it, take one SELL "
            f"macro from the net, and merge buys-first under the 10-order "
            f"cap.")

    # Multi-order head (2026-09-06, docs/RUNS.md verdict 33). K market slots
    # live in two extra arrays, msb and cmw. An npz without them plays slot 0
    # alone -- a one-order agent that banks money and passes every existing
    # check, so nothing downstream would notice: package.sh asserts money >
    # 3000 and tests/test_export_agent.py only covers the sheep option. Refuse.
    _mo = int(_ck_args.get("market_orders", 1) or 1)

    # 2026-08-28 (docs/RUNS.md 79c98d4). trl_env.py and macro_audit.py both run
    # the legacy adaptations here; this path did not, so any checkpoint predating
    # the hand-vocabulary expansion (anvil, chisel, cropper, longcredit -- 10
    # tasks against the runtime's 39) exported to an agent that answers PASS on
    # the opening state. The assertion at the end of this file is what caught it.
    #
    # new_bias=NEG, matching trl_env.py rather than train.py's 0.0: the 29 added
    # tasks were never trained in a legacy checkpoint, so at DEPLOYMENT they must
    # be suppressed to reproduce the behaviour that was actually learned.
    # train.py deliberately uses 0.0 instead, because it wants them learnable --
    # which is exactly why a warm start is not a faithful continuation, and why
    # attributing that arm's result to its own flag was not sound.
    sys.path.insert(0, os.path.join(_RL, "tensor_env"))
    from trl_policy import (NEG as _NEG, adapt_legacy_hand_head,
                            adapt_legacy_observation)
    sd, _obs_compat = adapt_legacy_observation(sd, O.OBS_DIM)
    sd, _hand_compat = adapt_legacy_hand_head(sd, new_bias=_NEG)
    if _obs_compat or _hand_compat:
        print(f"export: adapted legacy checkpoint "
              f"(obs={_obs_compat or 'ok'}, hands={_hand_compat or 'ok'})")
    # Depth cannot survive the plain-Policy export path: rl/policy.Policy has
    # no `extra` module, so load_state_dict(strict=False) drops every residual
    # block and the agent exports without a word as a depth-2 net -- plausible
    # opening action, verification assertion green. Refuse before the branch;
    # the array path below carries depth and gets its own post-condition.
    _depth = int(_ck_args.get("depth", 2) or 2)
    if _depth > 2 and not any(k.startswith(("base.", "hands.")) for k in sd):
        raise SystemExit(
            f"refusing to export {args.ckpt}: trained with --depth {_depth}, "
            f"but a plain two-head checkpoint takes the rl/policy.Policy path, "
            f"which has no residual blocks and would drop all {_depth - 2} of "
            f"them silently. Deep exports need --multi-head.")

    if any(k.startswith(("base.", "hands.")) for k in sd):
        # residual and/or multi-head checkpoints: ship raw arrays; the
        # main.py template understands every combination (a plain-Policy
        # load here would silently drop the hand heads -- a different agent)
        import types
        import numpy as np
        sys.path.insert(0, os.path.join(_RL, "tensor_env"))
        from trl_policy import actor_arrays

        if any(k.startswith("base.") for k in sd):
            arrays = actor_arrays(sd, "base.", numpy=True)
            arrays.update({f"d_{k}": v for k, v in
                           actor_arrays(sd, "delta.", numpy=True).items()})
        else:
            arrays = actor_arrays(sd, numpy=True)
        if _mo > 1:
            # Checked on the ARRAYS, not on the checkpoint. The first version of
            # this guard read ck["args"] and sd["slot_bias"], both of which were
            # present, and passed while actor_arrays -- which did not yet know
            # the two tables -- dropped them: the exported agent emitted one
            # order on all 719 turns. A pre-condition cannot catch a lossy
            # writer; only reading back what was written can.
            if "msb" not in arrays or "cmw" not in arrays:
                raise SystemExit(
                    f"refusing to export {args.ckpt}: trained with "
                    f"--market-orders {_mo} but the npz would carry "
                    f"{sorted(arrays)} -- no msb/cmw, so the agent would "
                    f"silently play slot 0 alone. Capping closer_cleo at one "
                    f"order a turn measures -89,479 (docs/RUNS.md verdict 33).")
            if int(arrays["msb"].shape[0]) != _mo:
                raise SystemExit(
                    f"refusing to export {args.ckpt}: --market-orders {_mo} "
                    f"but msb has {int(arrays['msb'].shape[0])} rows")
        # Same post-condition for depth. A plain (non-multi-head) deep actor
        # falls through to rl/policy.Policy, which has no `extra` module, and
        # load_state_dict(strict=False) drops every residual block without a
        # word: the agent exports, opens with a plausible action and is a
        # depth-2 net. Read back what is about to be written.
        if _depth > 2:
            _blocks = sum(1 for k in arrays if k.endswith("aw")
                          and k.startswith("e"))
            if _blocks != _depth - 2:
                raise SystemExit(
                    f"refusing to export {args.ckpt}: trained with --depth "
                    f"{_depth} but the npz would carry {_blocks} residual "
                    f"blocks, not {_depth - 2}. The agent would silently be a "
                    f"depth-2 net.")
        policy = types.SimpleNamespace(
            export_npz=lambda path: np.savez(path, **arrays))
    else:
        hidden = ck.get("hidden", [512, 256])
        policy = Policy(O.OBS_DIM, A.N_FARMER, A.N_MARKET, *hidden)
        # strict=False: pre-value-net checkpoints lack v1/v2 keys, and the
        # value net never ships anyway -- only the policy side is exported.
        policy.load_state_dict(sd, strict=False)
    main_path = write_agent_dir(
        policy, out_dir, temperature=args.sample,
        sheep_cash_max=args.sheep_cash_max,
        sheep_min_day=args.sheep_min_day, sheep_timeout=args.sheep_timeout)
    fn = get_last_callable(main_path)
    from kg_env import KGEnv
    raw = KGEnv(opponent="starter").reset(seed=123)
    act = fn(raw)
    assert isinstance(act, dict) and set(act) == {"farmer", "hands", "market"}, act
    assert act["farmer"] != ["PASS"] or act["market"], \
        "exported agent answers PASS/no-op on the opening state -- suspicious"
    # rl-baseline checkpoints carry global_step/stage; torchrl ones iter/algo
    step = ck.get("global_step", ck.get("iter"))
    step_s = f"{step:,}" if isinstance(step, int) else "?"
    print(f"exported {out_dir}  (ckpt step {step_s}, "
          f"stage {ck.get('stage', ck.get('algo'))})")
    print(f"opening action: {act['farmer']} market {act['market']}")


if __name__ == "__main__":
    main()
