#!/usr/bin/env python
"""Export a trained checkpoint as a torch-free, self-contained agent directory.

    python rl/export_agent.py --ckpt rl/runs/m1/latest.pt --name groundhog

Produces rl/out/<name>/ holding main.py (numpy forward, greedy argmax),
weights.npz, and private copies of obs.py / actions.py / kg_rules.py so the
directory works anywhere the loader puts it on sys.path -- locally under
tools/eval.py and unpacked flat in /kaggle_simulations/agent/ alike.

Verifies the way CLAUDE.md demands: emulates get_last_callable on the written
file and asks the loaded function for an answer on a real reset observation.
"""

import argparse
import os
import shutil
import sys

_RL = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_RL)
sys.path.insert(0, _RL)

MAIN_TEMPLATE = '''"""RL policy agent: numpy MLP forward, greedy argmax over masked heads.
Generated by rl/export_agent.py -- do not hand-edit; retrain and re-export.

No __file__ here: get_last_callable execs this source with empty globals and
only *appends* the agent directory to sys.path. Sibling modules carry names
unique to THIS export ({sfx}): unique vs other repo agents because of the
kg_rl_ prefix, and unique vs our *own* other exports because two of them in
one process would otherwise share sys.modules entries -- the second agent
would silently read the first one's weights via the cached module __file__
(observed: two different checkpoints playing byte-identical episodes).
"""

import os

import numpy as np

import kg_rl_obs_{sfx} as _O
import kg_rl_actions_{sfx} as _A

_W = dict(np.load(os.path.join(
    os.path.dirname(os.path.abspath(_O.__file__)), "weights.npz")))


def _forward(x):
    h = np.maximum(0.0, _W["l1w"] @ x + _W["l1b"])
    h = np.maximum(0.0, _W["l2w"] @ h + _W["l2b"])
    return _W["fw"] @ h + _W["fb"], _W["mw"] @ h + _W["mb"]


def _act(obs_dict):
    x = _O.encode(obs_dict)
    flog, mlog = _forward(x)
    flog[~_A.farmer_mask(obs_dict)] = -1e9
    mlog[~_A.market_mask(obs_dict)] = -1e9
    return _A.decode(obs_dict, int(flog.argmax()), int(mlog.argmax()))


def agent(obs, config=None):
    try:
        return _act(obs)
    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
'''


def get_last_callable(path):
    """Faithful emulation of kaggle_environments.agent.get_last_callable:
    empty globals (no __file__), agent dir *appended* to sys.path."""
    with open(path) as f:
        code = compile(f.read(), path, "exec")
    env = {}
    sys.path.append(os.path.dirname(path))
    try:
        exec(code, env)
    finally:
        sys.path.pop()
    callables = [v for v in env.values() if callable(v)]
    return callables[-1] if callables else None


def write_agent_dir(policy, out_dir):
    """Write a ready-to-run numpy agent directory for `policy` and verify the
    loader contract statically. Shared by the CLI export and league promotion.

    Module names are suffixed with this export's identity: kg_rules is the
    shared rules mirror (collisions are harmless by design), but obs/actions
    must be unique per export or two of our agents in one process share the
    cached module and the second reads the first's weights."""
    import re
    os.makedirs(out_dir, exist_ok=True)
    sfx = re.sub(r"\W", "_", os.path.basename(os.path.normpath(out_dir)))
    policy.export_npz(os.path.join(out_dir, "weights.npz"))
    for src, dst in ((os.path.join(_RL, "obs.py"), f"kg_rl_obs_{sfx}.py"),
                     (os.path.join(_RL, "actions.py"), f"kg_rl_actions_{sfx}.py"),
                     (os.path.join(_REPO, "agents", "kg_rules.py"), "kg_rules.py")):
        shutil.copy(src, os.path.join(out_dir, dst))
    main_path = os.path.join(out_dir, "main.py")
    with open(main_path, "w") as f:
        f.write(MAIN_TEMPLATE.replace("{sfx}", sfx))
    fn = get_last_callable(main_path)
    assert fn is not None and fn.__name__ == "agent", \
        f"last callable is {fn}, expected the agent"
    return main_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--out", default=os.path.join(_RL, "out"))
    args = ap.parse_args()

    import torch
    from policy import Policy
    import actions as A
    import obs as O

    out_dir = os.path.join(args.out, args.name)

    ck = torch.load(args.ckpt, map_location="cpu", weights_only=False)
    hidden = ck.get("hidden", [512, 256])
    policy = Policy(O.OBS_DIM, A.N_FARMER, A.N_MARKET, *hidden)
    # strict=False: pre-value-net checkpoints lack v1/v2 keys, and the value
    # net never ships anyway -- only the policy side is exported.
    policy.load_state_dict(ck["model"], strict=False)
    main_path = write_agent_dir(policy, out_dir)
    fn = get_last_callable(main_path)
    from kg_env import KGEnv
    raw = KGEnv(opponent="starter").reset(seed=123)
    act = fn(raw)
    assert isinstance(act, dict) and set(act) == {"farmer", "hands", "market"}, act
    assert act["farmer"] != ["PASS"] or act["market"], \
        "exported agent answers PASS/no-op on the opening state -- suspicious"
    # rl-baseline checkpoints carry global_step/stage; torchrl ones iter/algo
    step = ck.get("global_step", ck.get("iter"))
    step_s = f"{step:,}" if isinstance(step, int) else "?"
    print(f"exported {out_dir}  (ckpt step {step_s}, "
          f"stage {ck.get('stage', ck.get('algo'))})")
    print(f"opening action: {act['farmer']} market {act['market']}")


if __name__ == "__main__":
    main()
