#!/usr/bin/env python
"""Export a --fixed-farm-tape checkpoint: the tape's farm, the net's SELL.

    python rl/export_hybrid.py --ckpt rl/runs/sell-n04/best.pt --name sell-n04

`rl/export_agent.py` REFUSES such a checkpoint, and correctly: under
--fixed-farm-tape the farm program (farmer + every hand slot) and every
non-SELL market order are grafted from a tape at the raw-op level, so only
SELL received an objective. `MarketOnlyMultiHead` is a parameterless
distribution subclass, so the state dict is shape-indistinguishable from a
plain --multi-head run, and the ordinary export path would hand farmer, all
twelve hand slots and the full 31-way market mask straight back to heads that
were never trained -- and that are worse than untrained, because they sit on
the shared l1/l2 trunk and drift with the market head's gradient. That is how
8db606f's --fixed-market-profile arm became undeliverable at a measured -33%.

So this exporter writes the mirror of what training did:

    farmer  <- tape[step]["farmer"]
    hands   <- tape[step]["hands"]
    market  <- [o for o in tape[step]["market"] if o[0] != "SELL"]
               + the net's one decoded market option,
               buys first, truncated at kg_rules.MAX_ORDERS

Buys go first for the same reason `engine_t_idx.step_idx`'s `m_add` packs them
first: the engine settles slots in order, so a purchase is worthless once a
sale has eaten the slot budget. Truncation is real -- orders are capped at 10
and a tape turn can carry that many by itself.

At inference the merge is EASIER than in training. Training had to graft raw
ops through `step_overrides` because the tape lives in raw op space
(f_op/f_arg/f_qty) while the farmer head is a macro index and the macro decode
cannot express every raw op. Here both sides are plain action lists, so there
is no translation at all.

Two differences from `sharedmeta-cleo` (the live submission) that are
deliberate and must be read into any comparison:

* The tape replayed here is `mod._TRACE`, the mined PLAN -- exactly what
  training grafted, and NOT the plan as `agents/newlines/*.py` plays it. That
  file wraps the plan in closer_cleo's layer, whose `_terminal_action` replaces
  the plan entirely from step 714 and whose `_terminal_liquidation` starts at
  680. Our net has to learn the endgame itself. It can: `actions._market_action`
  makes `SELL_<p>` sell the whole shed on and after the liquidation day.
* Nothing here reorders the tape's own sells, because they are dropped
  entirely -- SELL is the net's whole job.

Provenance, unchanged from the live submission: the `_TRACE` is a shared meta
line reconstructed from public replays and is not ours; the SELL layer is.
`tools/hybrid.py` bans snapshotting tape hybrids into `submissions/` without a
decision from the user, and that decision is the user's alone.
"""

import argparse
import base64
import json
import os
import re
import shutil
import sys
import zlib

_RL = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_RL)
sys.path.insert(0, _RL)

# Substituted with plain str.replace, so braces here are literal.
MAIN_TEMPLATE = '''"""Tape farm + learned SELL layer. Generated by rl/export_hybrid.py.

Do not hand-edit; retrain and re-export.

The farm program is replayed from the embedded plan (TAPE_NOTE) and the SELL
layer is a numpy MLP forward over the masked market head. The farmer and hand
heads in weights.npz are NOT consulted: under --fixed-farm-tape they received
no objective and drifted on the shared trunk, so consulting them would be the
8db606f failure (-33%, produced purely by an export path).

No __file__ here: get_last_callable execs this source with empty globals and
only *appends* the agent directory to sys.path. Sibling modules carry names
unique to THIS export (SFX) -- two exports in one process would otherwise
share sys.modules entries and the second would read the first one's weights.
"""

import base64 as _b64
import json as _js
import os
import zlib as _zl

import numpy as np

import kg_rl_obs_SFX as _O
import kg_rl_actions_SFX as _A
import kg_rules as _R

_W = dict(np.load(os.path.join(
    os.path.dirname(os.path.abspath(_O.__file__)), "weights.npz")))
_TAPE = _js.loads(_zl.decompress(_b64.b85decode("TAPEBLOB")).decode())
_PASS = {"farmer": ["PASS"], "hands": [], "market": []}
_MAXO = getattr(_R, "MAX_ORDERS", 10)


def _market_logits(x):
    h = np.maximum(0.0, _W["l1w"] @ x + _W["l1b"])
    h = np.maximum(0.0, _W["l2w"] @ h + _W["l2b"])
    return _W["mw"] @ h + _W["mb"]


def _sell_orders(obs):
    """The net's market option, decoded through the SAME public path training
    used. The farmer/hand arguments are placeholders: `_market_action` reads
    only the observation and the option name, so they cannot affect this."""
    mlog = _market_logits(_O.encode(obs))
    mask = np.asarray(_A.market_mask(obs), dtype=bool)
    mlog = np.where(mask, mlog, -1e9)
    m_idx = int(np.argmax(mlog))
    dec = _A.decode_multi(obs, 0, [0] * _A.MAX_HANDS, m_idx)
    return list(dec.get("market") or [])


def _act(obs):
    i = int(obs.get("step", 0) or 0)
    if not (0 <= i < len(_TAPE)):
        return _PASS
    t = _TAPE[i] or {}
    buys = [o for o in (t.get("market") or []) if o and o[0] != "SELL"]
    # buys first, then the net's option, truncated -- the engine settles slots
    # in order, so a purchase queued behind a sale is wasted
    market = (buys + _sell_orders(obs))[:_MAXO]
    return {"farmer": list(t.get("farmer") or ["PASS"]),
            "hands": [list(h) for h in (t.get("hands") or [])],
            "market": market}


def agent(obs, config=None):
    try:
        return _act(obs)
    except Exception:
        return _PASS
'''


def load_trace(agent_path):
    """The mined plan out of a wrapped agent file, the same way tape_t does."""
    sys.path.insert(0, os.path.join(_RL, "tensor_env"))
    import tape_t
    return tape_t.load_trace(agent_path)


def get_last_callable(path):
    """Faithful emulation of kaggle_environments.agent.get_last_callable."""
    src = open(path).read()
    env = {}
    d = os.path.dirname(os.path.abspath(path))
    sys.path.append(d)
    try:
        exec(src, env)
    finally:
        if d in sys.path:
            sys.path.remove(d)
    cs = [v for v in env.values() if callable(v)]
    return cs[-1] if cs else None


def write_hybrid_dir(arrays, trace, out_dir, tape_note="mined plan"):
    import numpy as np
    os.makedirs(out_dir, exist_ok=True)
    sfx = re.sub(r"\W", "_", os.path.basename(os.path.normpath(out_dir)))
    np.savez(os.path.join(out_dir, "weights.npz"), **arrays)
    for src, dst in ((os.path.join(_RL, "obs.py"), f"kg_rl_obs_{sfx}.py"),
                     (os.path.join(_RL, "actions.py"),
                      f"kg_rl_actions_{sfx}.py"),
                     (os.path.join(_REPO, "agents", "kg_rules.py"),
                      "kg_rules.py")):
        shutil.copy(src, os.path.join(out_dir, dst))
    blob = base64.b85encode(zlib.compress(
        json.dumps(trace).encode(), 9)).decode()
    # TAPE_NOTE before TAPEBLOB: the blob is inserted text, and replacing
    # into it afterwards could corrupt it.
    body = (MAIN_TEMPLATE.replace("SFX", sfx)
            .replace("TAPE_NOTE", tape_note)
            .replace("TAPEBLOB", blob))
    main_path = os.path.join(out_dir, "main.py")
    with open(main_path, "w") as f:
        f.write(body)
    fn = get_last_callable(main_path)
    assert fn is not None and fn.__name__ == "agent", \
        f"last callable is {fn}, expected the agent"
    return main_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--out", default=os.path.join(_RL, "out"))
    ap.add_argument("--tape", default="",
                    help="override the tape; default is the checkpoint's own "
                         "args['fixed_farm_tape'], which is what it trained on")
    args = ap.parse_args()

    import torch
    import obs as O
    sys.path.insert(0, os.path.join(_RL, "tensor_env"))
    from trl_policy import (NEG as _NEG, actor_arrays,
                            adapt_legacy_hand_head, adapt_legacy_observation)

    ck = torch.load(args.ckpt, map_location="cpu", weights_only=False)
    ck_args = ck.get("args") or {}
    tape = args.tape or ck_args.get("fixed_farm_tape") or ""
    if not tape:
        raise SystemExit(
            f"{args.ckpt} has no args['fixed_farm_tape'] and --tape was not "
            f"given. A hybrid export without a tape is just a broken ordinary "
            f"export; use rl/export_agent.py for a normal checkpoint.")
    mkt = ck_args.get("farm_tape_market")
    if mkt not in (None, "buys"):
        raise SystemExit(
            f"this checkpoint trained with --farm-tape-market {mkt!r}; only "
            f"'buys' leaves SELL as the trainable half, and only 'buys' "
            f"matches the merge this export writes")
    if not os.path.isabs(tape):
        tape = os.path.join(_REPO, tape)

    sd = ck["model"]
    sd, _oc = adapt_legacy_observation(sd, O.OBS_DIM)
    sd, _hc = adapt_legacy_hand_head(sd, new_bias=_NEG)
    if any(k.startswith("base.") for k in sd):
        raise SystemExit("residual checkpoints are not supported here yet")
    arrays = actor_arrays(sd, numpy=True)

    trace = load_trace(tape)
    out_dir = os.path.join(args.out, args.name)
    note = f"{os.path.relpath(tape, _REPO)}, {len(trace)} turns"
    main_path = write_hybrid_dir(arrays, trace, out_dir, tape_note=note)
    print(f"exported {out_dir}  (ckpt step "
          f"{ck.get('global_step', ck.get('iter'))}, tape {note})")

    # Verify the way CLAUDE.md demands: ask the LOADED function for a KNOWN
    # answer. Not merely "is it non-PASS" -- the farm must be the tape's, or
    # the graft is not wired and every later reading is void.
    fn = get_last_callable(main_path)
    from kg_env import KGEnv                             # noqa: E402
    obs0 = KGEnv(opponent="starter").reset(seed=123)
    act = fn(obs0)
    assert set(act) == {"farmer", "hands", "market"}, act
    want = list((trace[0] or {}).get("farmer") or ["PASS"])
    assert act["farmer"] == want, (
        f"step-0 farmer is {act['farmer']} but the tape says {want} -- the "
        f"graft is not wired")
    assert not any(o and o[0] == "SELL" for o in act["market"]
                   if o in ((trace[0] or {}).get("market") or [])), \
        "a tape SELL survived into the merged market"
    print(f"opening action: farmer {act['farmer']}  hands {len(act['hands'])}"
          f"  market {act['market']}")


if __name__ == "__main__":
    main()
