#!/usr/bin/env python
"""Export a trained checkpoint as a torch-free, self-contained agent directory.

    python rl/export_agent.py --ckpt rl/runs/m1/latest.pt --name groundhog

Produces rl/out/<name>/ holding main.py (numpy forward, greedy argmax),
weights.npz, and private copies of obs.py / actions.py / kg_rules.py so the
directory works anywhere the loader puts it on sys.path -- locally under
tools/eval.py and unpacked flat in /kaggle_simulations/agent/ alike.

Verifies the way CLAUDE.md demands: emulates get_last_callable on the written
file and asks the loaded function for an answer on a real reset observation.
"""

import argparse
import os
import shutil
import sys

_RL = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_RL)
sys.path.insert(0, _RL)

MAIN_TEMPLATE = '''"""RL policy agent: numpy MLP forward, greedy argmax over masked heads.
Generated by rl/export_agent.py -- do not hand-edit; retrain and re-export."""

import os
import sys

_D = os.path.dirname(os.path.abspath(__file__))
if _D not in sys.path:
    sys.path.insert(0, _D)

import numpy as np

import obs as _O
import actions as _A

_W = dict(np.load(os.path.join(_D, "weights.npz")))


def _forward(x):
    h = np.maximum(0.0, _W["l1w"] @ x + _W["l1b"])
    h = np.maximum(0.0, _W["l2w"] @ h + _W["l2b"])
    return _W["fw"] @ h + _W["fb"], _W["mw"] @ h + _W["mb"]


def _act(obs_dict):
    x = _O.encode(obs_dict)
    flog, mlog = _forward(x)
    flog[~_A.farmer_mask(obs_dict)] = -1e9
    mlog[~_A.market_mask(obs_dict)] = -1e9
    return _A.decode(obs_dict, int(flog.argmax()), int(mlog.argmax()))


def agent(obs, config=None):
    try:
        return _act(obs)
    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
'''


def get_last_callable(path):
    env = {}
    with open(path) as f:
        code = compile(f.read(), path, "exec")
    exec(code, env)
    callables = [v for v in env.values() if callable(v)]
    return callables[-1] if callables else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--out", default=os.path.join(_RL, "out"))
    args = ap.parse_args()

    import torch
    from policy import Policy
    import actions as A
    import obs as O

    out_dir = os.path.join(args.out, args.name)
    os.makedirs(out_dir, exist_ok=True)

    ck = torch.load(args.ckpt, map_location="cpu", weights_only=False)
    policy = Policy(O.OBS_DIM, A.N_FARMER, A.N_MARKET)
    policy.load_state_dict(ck["model"])
    policy.export_npz(os.path.join(out_dir, "weights.npz"))

    for src in (os.path.join(_RL, "obs.py"), os.path.join(_RL, "actions.py"),
                os.path.join(_REPO, "agents", "kg_rules.py")):
        shutil.copy(src, out_dir)
    main_path = os.path.join(out_dir, "main.py")
    with open(main_path, "w") as f:
        f.write(MAIN_TEMPLATE)

    fn = get_last_callable(main_path)
    assert fn is not None and fn.__name__ == "agent", \
        f"last callable is {fn}, expected the agent"
    from kg_env import KGEnv
    raw = KGEnv(opponent="starter").reset(seed=123)
    act = fn(raw)
    assert isinstance(act, dict) and set(act) == {"farmer", "hands", "market"}, act
    assert act["farmer"] != ["PASS"] or act["market"], \
        "exported agent answers PASS/no-op on the opening state -- suspicious"
    print(f"exported {out_dir}  (ckpt step {ck.get('global_step'):,}, "
          f"stage {ck.get('stage')})")
    print(f"opening action: {act['farmer']} market {act['market']}")


if __name__ == "__main__":
    main()
