"""RL policy agent: numpy MLP forward over masked heads.
Inference mode is baked at export: greedy argmax (default) or softmax
sampling (--sample T) -- measured on this line's checkpoints, sampling is
worth 10-30pp against recording-lineage opponents (argmax mode collapse)
and costs ~10k margin against reactive ones; pick per destination.
Generated by rl/export_agent.py -- do not hand-edit; retrain and re-export.

No __file__ here: get_last_callable execs this source with empty globals and
only *appends* the agent directory to sys.path. Sibling modules carry names
unique to THIS export (cropper_samp): unique vs other repo agents because of the
kg_rl_ prefix, and unique vs our *own* other exports because two of them in
one process would otherwise share sys.modules entries -- the second agent
would silently read the first one's weights via the cached module __file__
(observed: two different checkpoints playing byte-identical episodes).
"""

import os

import numpy as np

import kg_rl_obs_cropper_samp as _O
import kg_rl_actions_cropper_samp as _A

_W = dict(np.load(os.path.join(
    os.path.dirname(os.path.abspath(_O.__file__)), "weights.npz")))


def _forward(x):
    h = np.maximum(0.0, _W["l1w"] @ x + _W["l1b"])
    h = np.maximum(0.0, _W["l2w"] @ h + _W["l2b"])
    f, m = _W["fw"] @ h + _W["fb"], _W["mw"] @ h + _W["mb"]
    hl = _W["hw"] @ h + _W["hb"] if "hw" in _W else None
    if "d_l1w" in _W:  # residual export: frozen prior + learned correction
        h = np.maximum(0.0, _W["d_l1w"] @ x + _W["d_l1b"])
        h = np.maximum(0.0, _W["d_l2w"] @ h + _W["d_l2b"])
        f = f + _W["d_fw"] @ h + _W["d_fb"]
        m = m + _W["d_mw"] @ h + _W["d_mb"]
        if "d_hw" in _W:  # multi-head hands live on the delta trunk
            hl = _W["d_hw"] @ h + _W["d_hb"]
    return f, m, hl


_TEMP = 1.0   # 0 = greedy argmax; >0 = softmax sampling at this temperature
_RNG = np.random.default_rng(20260820)


def _pick(logits):
    if _TEMP <= 0.0:
        return int(logits.argmax())
    z = (logits - logits.max()) / _TEMP
    p = np.exp(z)
    p /= p.sum()
    return int(_RNG.choice(len(p), p=p))


def _act(obs_dict):
    x = _O.encode(obs_dict)
    flog, mlog, hlog = _forward(x)
    flog[~_A.farmer_mask(obs_dict)] = -1e9
    mlog[~_A.market_mask(obs_dict)] = -1e9
    if hlog is None:
        return _A.decode(obs_dict, _pick(flog), _pick(mlog))
    hm = np.array(_A.hand_task_mask(obs_dict), dtype=bool)
    hlog = hlog.reshape(hm.shape)
    hlog[~hm] = -1e9
    tasks = [_pick(row) for row in hlog]
    return _A.decode_multi(obs_dict, _pick(flog), tasks, _pick(mlog))


def agent(obs, config=None):
    try:
        return _act(obs)
    except Exception:
        return {"farmer": ["PASS"], "hands": [], "market": []}
