#!/bin/bash
# Build this project's virtualenv from scratch. Run once per checkout:
#
#     bash tools/bootstrap.sh
#     source setup_env.sh
#
# Works on the Vulcan cluster and on an ordinary laptop. It detects which one it
# is on and takes the faster path where available; the result is the same
# environment either way. Safe to re-run -- it recreates venv/ in place.
#
#     bash tools/bootstrap.sh --freeze    # only refresh requirements/lock.txt

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# --- --freeze: snapshot the current venv and stop -----------------------------
if [ "${1:-}" = "--freeze" ]; then
    source "$ROOT/venv/bin/activate"
    {
        echo "# Generated by tools/bootstrap.sh --freeze on $(date +%F)."
        echo "# A snapshot of a known-good environment, for auditing and for"
        echo "# reproducing an exact setup. NOT consumed by bootstrap."
        echo "#"
        echo "# Taken on the Vulcan cluster: versions carrying a '+computecanada'"
        echo "# local suffix exist only in that wheelhouse, so this file does not"
        echo "# install cleanly elsewhere. Use requirements/base.txt for that."
        echo "#"
        echo "# python $(python -V 2>&1 | cut -d' ' -f2)"
        echo
        pip freeze --local | sort
    } > "$ROOT/requirements/lock.txt"
    echo "wrote requirements/lock.txt"
    exit 0
fi

# --- Detect the platform ------------------------------------------------------
# Lmod exports these; neither exists on a personal machine.
if [ -n "${LMOD_CMD:-}${MODULESHOME:-}" ]; then
    ON_CLUSTER=1
else
    ON_CLUSTER=0
fi

echo "project root : $ROOT"
echo "platform     : $([ "$ON_CLUSTER" = 1 ] && echo 'HPC cluster (Lmod detected)' || echo 'local machine')"

# --- 1. Pin the interpreter ---------------------------------------------------
if [ "$ON_CLUSTER" = 1 ]; then
    # Never pipe `module load` -- a pipe runs it in a subshell and the
    # environment change is silently lost. This cost an afternoon once.
    module purge
    module load python/3.11.5
    PY=python3
else
    # Any 3.9+ works; 3.11 is what the cluster and Kaggle's runtime use.
    PY="${PYTHON:-python3}"
    if ! command -v "$PY" >/dev/null 2>&1; then
        echo "error: no '$PY' on PATH. Install Python 3.9+ or set PYTHON=/path/to/python3" >&2
        exit 1
    fi
    "$PY" - <<'EOF' || { echo "error: need Python >= 3.9" >&2; exit 1; }
import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)
EOF
fi
echo "python       : $($PY -V 2>&1)"

# --- 2. Virtualenv ------------------------------------------------------------
"$PY" -m venv --clear "$ROOT/venv"
source "$ROOT/venv/bin/activate"
unset PIP_PREFIX          # the cluster presets this and it fights venvs
python -m pip install --quiet --upgrade pip

# --- 3. Base dependencies -----------------------------------------------------
if [ "$ON_CLUSTER" = 1 ]; then
    # The cluster wheelhouse is compiled for these nodes: seconds instead of
    # minutes, and no ABI surprises. Fall through to PyPI if it is unavailable.
    echo "installing numpy/pandas from the cluster wheelhouse..."
    pip install --quiet --no-index numpy pandas || {
        echo "  wheelhouse unavailable, falling back to PyPI"
        pip install --quiet numpy pandas
    }
    echo "installing the rest from PyPI..."
    pip install --quiet kaggle kagglehub jupytext
else
    echo "installing base dependencies from PyPI..."
    pip install --quiet -r "$ROOT/requirements/base.txt"
fi

# --- 4. The competition environment, WITHOUT its dependency tree --------------
# See requirements/nodeps.txt for the full explanation.
echo "installing kaggle-environments (--no-deps on purpose)..."
pip install --quiet --no-deps --upgrade -r "$ROOT/requirements/nodeps.txt"

# --- 5. Verify with a real episode -------------------------------------------
echo
echo "verifying..."
python - <<'PY'
from kaggle_environments import make
env = make("kaggriculture", configuration={"episodeSteps": 48, "seed": 1})
env.run(["starter", "random"])
assert all(s.status == "DONE" for s in env.steps[-1]), "episode did not finish"
print(f"  short episode ran clean: {[float(s.reward or 0) for s in env.steps[-1]]}")
PY

mkdir -p "$ROOT/.kaggle" "$ROOT/data" "$ROOT/logs" "$ROOT/site"
chmod 700 "$ROOT/.kaggle"

cat <<EOF

bootstrap complete.

Next:
  1. Put your Kaggle credentials in $ROOT/.kaggle/
       kaggle.json      {"username": "...", "key": "..."}
     and/or
       access_token     a plain-text KGAT_... token
     chmod 600 both. They stay in this directory -- setup_env.sh points
     KAGGLE_CONFIG_DIR here, so copies under \$HOME are never used.

  2. source setup_env.sh
  3. python tools/registry.py gen --plan all --out agents/lib
  4. Read docs/ONBOARDING.md
EOF
