#!/usr/bin/env python
"""Build agents/monger/: the tape's farm + a MEASURED slicing SELL layer.

    python tools/build_monger.py --tape agents/newlines/n04.py --keep 0.90

Every constant in the sell rule came out of `tools/liquidate.py` on the file
that is live on the ladder (docs/RUNS.md 2026-09-04 continuation eleven), and
each one refuted a plausible alternative:

* The book barely moves over a season (MILK -8..+76, WOOL -7..+59 on seed
  555) because `_town_consume` draws it down every four steps. The loss is
  the INTRA-TURN walk: `_process_market` quotes each unit at the live
  inventory and calls `_refresh_prices` only at the end of the phase. So the
  rule caps the per-turn quantity, and does NOT schedule across days.
* There is no intra-day phase edge to exploit: the pre-market price by
  step % 4, recovered from the snapshots, is flat at 1.00x-1.09x. An earlier
  reading of 2.45x was the tape's own uneven sell schedule confounded with
  season position, not a phase effect.
* The shed does NOT bind: seat-0 occupancy was median 16, p90 50, max 89 of
  100 across 719 steps, and never touched 95. Holding units back to slice
  them is therefore free -- but `_drop_inventories` DISCARDS overflow, so the
  rule still dumps when occupancy gets high.
* Slicing is NOT always right. Measured per-seed gain from slicing was
  NEGATIVE for MELON (-8,466, identical on all five seeds), FERTILIZER and
  WHEAT. MELON has no shop at all -- its only demand is the town centre's
  1/day -- so its book never recovers and the right play is to get there
  before the opponent. Hence the race test below, which is evaluated at
  RUNTIME because it depends on the shop draw: WOOL is a slice when a
  YARN_STORE unlocked (12/day) and a race when none did (1/day).

The race test needs to know how much is still coming, and under a frozen farm
tape that is knowable exactly: the tape's own SELL quantities are its
production. They are embedded per product at build time.
"""

import argparse
import base64
import json
import os
import shutil
import sys
import zlib

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(_REPO, "rl", "tensor_env"))

MAIN = '''"""Tape farm + slicing SELL layer. Generated by tools/build_monger.py.

Do not hand-edit; rebuild. Provenance: the farm plan is a shared meta line
reconstructed from public replays and is not ours; the SELL layer is.
"""

import base64 as _b64
import json as _js
import math as _m
import zlib as _zl

import kg_rules as _R

_TAPE = _js.loads(_zl.decompress(_b64.b85decode("TAPEBLOB")).decode())
_KEEP = KEEPVAL
_SHED_HI = SHEDHI
_STEPS = len(_TAPE)
_PASS = {"farmer": ["PASS"], "hands": [], "market": []}
_SINGLE = {s for s, v in _R.SHOPS.items() if len(v) == 1} if hasattr(
    _R, "SHOPS") else set()
_SHOPS = getattr(_R, "SHOPS", {})
_CENTRE = [p for p in _R.PRODUCTS if p != "FERTILIZER"]


def _cons_per_turn(obs, item):
    """Units of `item` the town absorbs per turn, from the CURRENT shop draw.

    Shops keep unlocking, so this understates future demand -- which biases
    the race test toward racing, i.e. toward the behaviour the measurement
    says is safe (cleo's static layer already wins the melon race)."""
    shops = ((obs.get("town") or {}).get("unlocked_shops") or [])
    per_day = 0.0
    for s in shops:
        prods = _SHOPS.get(s) or []
        if item in prods:
            per_day += 6.0 * (2.0 if len(prods) == 1 else 1.0)
    if item in _CENTRE:
        per_day += 1.0
    return per_day / 24.0


def _depth(item, inv, keep):
    """How many units can go out this turn before the marginal price falls
    below `keep` of the opening price. The walk is what costs money."""
    p0 = _R.market_price(item, inv)
    if p0 <= 1:
        return 1
    lo, hi = 1, 256
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if _R.market_price(item, inv + mid - 1) >= keep * p0:
            lo = mid
        else:
            hi = mid - 1
    return max(1, lo)


def _sells(obs):
    """RE-TIME the tape's own sells. Never add one, never bring one forward.

    The first version sold anything sitting in the shed and lost 60k a game:
    the tape BUYS wheat and fertilizer as inputs (feed, fertiliser), so a
    layer that sells what it finds destroys the farm's own supply -- measured,
    money 78,949 -> 17,096 and the opponent 50,528 -> 95,002 on seed 555,
    because a farm that eats its inputs also stops competing for the book.
    (`nofeedsell-0902` in data/shards is this same family.)

    So the pending queue is the tape's cumulative SELL quantity minus what we
    have actually sold. A unit can only be sold on the tape's own turn or
    LATER, which is exactly the delay-only intervention the bound measured
    (docs/RUNS.md 2026-09-04 continuation eleven), and the sell set is
    identical to the tape's by construction."""
    inv = (obs.get("market") or {}).get("inventory") or {}
    shed = (obs.get("private") or {}).get("shed") or {}
    step = int(obs.get("step", 0) or 0)
    if step == 0:
        _pend.clear()
    left = max(1, _STEPS - step)
    load = sum(max(0, int(v or 0)) for v in shed.values())
    for o in ((_TAPE[step] or {}).get("market") or []):
        if o and o[0] == "SELL" and len(o) > 2:
            _pend[o[1]] = _pend.get(o[1], 0) + int(o[2])
    out = []
    # highest current price first: the engine settles slots in order, so the
    # most valuable sale must take the earliest slot
    items = [i for i in _pend
             if _pend[i] > 0 and int(shed.get(i, 0) or 0) > 0]
    items.sort(key=lambda i: -_R.market_price(i, int(inv.get(i, 10000) or 0)))
    for item in items:
        want = min(_pend[item], int(shed[item] or 0))
        iv = int(inv.get(item, 10000) or 0)
        rate = _cons_per_turn(obs, item)
        if _pend[item] > rate * left or load >= _SHED_HI:
            qty = want          # race, or the shed is about to discard
        else:
            pace = int(_m.ceil(_pend[item] / float(left)))
            qty = min(want, max(_depth(item, iv, _KEEP), pace))
        if qty > 0:
            out.append(["SELL", item, int(qty)])
            _pend[item] -= int(qty)
    return out


_pend = {}


def _act(obs):
    i = int(obs.get("step", 0) or 0)
    if not (0 <= i < _STEPS):
        return _PASS
    t = _TAPE[i] or {}
    buys = [o for o in (t.get("market") or []) if o and o[0] != "SELL"]
    market = (buys + _sells(obs))[:getattr(_R, "MAX_ORDERS", 10)]
    return {"farmer": list(t.get("farmer") or ["PASS"]),
            "hands": [list(h) for h in (t.get("hands") or [])],
            "market": market}


def agent(obs, config=None):
    try:
        return _act(obs)
    except Exception:
        return _PASS
'''


def get_last_callable(path):
    src = open(path).read()
    env = {}
    d = os.path.dirname(os.path.abspath(path))
    sys.path.append(d)
    try:
        exec(src, env)
    finally:
        if d in sys.path:
            sys.path.remove(d)
    cs = [v for v in env.values() if callable(v)]
    return cs[-1] if cs else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tape", default="agents/newlines/n04.py")
    ap.add_argument("--out", default="agents/monger")
    ap.add_argument("--keep", type=float, default=0.90,
                    help="per-turn price retention: sell while the marginal "
                         "unit still fetches this fraction of the opening price")
    ap.add_argument("--shed-hi", type=int, default=85,
                    help="dump everything above this shed load; overflow is "
                         "discarded by _drop_inventories, not carried")
    args = ap.parse_args()

    import tape_t
    tape = os.path.join(_REPO, args.tape) if not os.path.isabs(args.tape) \
        else args.tape
    trace = tape_t.load_trace(tape)
    vol = {}
    for t in trace:
        for o in (t or {}).get("market") or []:
            if o and o[0] == "SELL" and len(o) > 2:
                vol[o[1]] = vol.get(o[1], 0) + int(o[2])
    out_dir = os.path.join(_REPO, args.out)
    os.makedirs(out_dir, exist_ok=True)
    shutil.copy(os.path.join(_REPO, "agents", "kg_rules.py"),
                os.path.join(out_dir, "kg_rules.py"))
    blob = base64.b85encode(zlib.compress(
        json.dumps(trace).encode(), 9)).decode()
    body = (MAIN.replace("KEEPVAL", repr(float(args.keep)))
            .replace("SHEDHI", repr(int(args.shed_hi)))
            .replace("VOLJSON", json.dumps(vol).replace('"', '\\"'))
            .replace("TAPEBLOB", blob))
    path = os.path.join(out_dir, "main.py")
    open(path, "w").write(body)

    fn = get_last_callable(path)
    assert fn is not None and fn.__name__ == "agent", f"last callable {fn}"
    print(f"wrote {path}  (tape {os.path.relpath(tape, _REPO)}, "
          f"{len(trace)} turns, keep={args.keep}, shed_hi={args.shed_hi})")
    print(f"tape season volume: "
          + ", ".join(f"{k} {v}" for k, v in sorted(vol.items(),
                                                    key=lambda kv: -kv[1])))


if __name__ == "__main__":
    main()
