#!/usr/bin/env python
"""Turn a top-of-the-leaderboard trajectory into a local opponent.

The echo chamber problem, stated plainly: every agent in `agents/lib` shares one
execution path, so a tournament between them measures which *configuration* of
that path is best and can never measure the path itself. `agents/spar/` was an
attempt to escape it by fitting atom configurations to real opponents' digests,
and it does not: a fitted configuration still runs on our engine, which works
21-27% of its actions where the top of the ladder works 40.6%.

A **ghost** does not fit anything. It replays the recorded action sequence of a
3,100-rated player, turn by turn, exactly as that player issued it.

    python tools/ghost.py make --date 2026-08-09 --limit 20
    python tools/ghost.py verify --limit 8

The seed matters. `configuration.seed` is scrubbed from the replay so agents
cannot read it, but `info.seed` survives, and replaying on that seed gives the
ghost the same starting board it actually played. `tools/tournament.py` is told
the seed through the manifest.

**What a ghost is not.** It is open-loop: it cannot react to us. Its farm work is
largely independent of what we do, but its market timing is stale, and the weed
RNG is shared between both farms and scales with each one's empty tiles — so our
different play perturbs its board too. `verify` measures exactly how much of its
original score a ghost still reaches, and refuses to ship one that collapses.
"""

import argparse
import base64
import gzip
import json
import os
import random
import sys
from collections import Counter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from kaggle_cli import dataset_file, dataset_files

# Final-money bands. A day's dump spans $31k to $139k and a field of only the
# extremes measures something other than the ladder.
BANDS = [(0, 60_000, "low"), (60_000, 90_000, "mid"),
         (90_000, 115_000, "high"), (115_000, 10**9, "top")]


def _band(score):
    for lo, hi, name in BANDS:
        if lo <= score < hi:
            return name
    return "top"


def cmd_balance(args):
    """What the current field is made of. Run it before trusting a measurement."""
    import statistics as st
    with open(os.path.join(OUT, "manifest.json")) as f:
        m = json.load(f)
    print(f"{len(m)} ghosts\n")
    tc = Counter(v.get("team") for v in m.values())
    print(f"  {len(tc)} teams, largest share {tc.most_common(1)[0][1]/len(m):.0%}")
    for t, n in tc.most_common(8):
        print(f"    {n:>3d}  {t}")
    bc = Counter(v.get("band", _band(v["original_score"])) for v in m.values())
    print("\n  score bands:")
    for _lo, _hi, name in BANDS:
        print(f"    {name:5s} {bc.get(name, 0):>3d}")
    dc = Counter(str(v.get("date", "?")) for v in m.values())
    print("\n  days:")
    for d, n in sorted(dc.items()):
        print(f"    {d} {n:>3d}")
    sc = [v["original_score"] for v in m.values()]
    print(f"\n  score median ${st.median(sc):,.0f}  "
          f"min ${min(sc):,.0f}  max ${max(sc):,.0f}")
    return 0

OUT = "agents/ghosts"
WORK = "data/topeps"

TEMPLATE = '''"""Ghost of {team} — episode {ep}, seat {seat}, original score ${score:,.0f}.

Not a strategy. The recorded action sequence of a player rated ~3,100, replayed
turn by turn. Generated by tools/ghost.py; do not edit.

Open-loop: it cannot react. Replay on seed {seed} to give it the board it played.
"""

import base64
import gzip
import json

_SEED = {seed}
_TURNS = json.loads(gzip.decompress(base64.b64decode(
    "{blob}"
)).decode())
_PASS = {{"farmer": ["PASS"], "hands": [], "market": []}}


def agent(obs):
    try:
        i = int(obs.get("step", 0) or 0)
        a = _TURNS[i] if 0 <= i < len(_TURNS) else None
        return a if a else _PASS
    except Exception:
        return _PASS
'''


def _fetch(date, name):
    return dataset_file(f"kaggle/kaggriculture-episodes-{date}", name, WORK)


def cmd_make(args):
    """Sample a ghost field rather than taking whatever comes first.

    Three biases have to be designed out, and none of them is visible until you
    look at the composition of a naive pull:

    **One player dominating.** Taking the first N files gave 12% of the field to
    a single team, so a third of the "opponents" were three copies of one policy.
    `--per-team` caps it.

    **A narrow time window.** The listing is ordered by episode id, which is
    time, so the first N files are all from the same hour of the same day.
    `--dates` samples round-robin across days, which also captures meta drift.

    **No spread in strength.** A day's dump ranges from $31k to $139k of final
    money. A field that is all extremes measures something other than the ladder.
    `--bands` fills score quartiles evenly.

    The metadata only exists inside the 32 MB file, so the caps are applied
    *after* download and an over-quota episode is discarded. That wastes some
    bandwidth and is the price of an unbiased sample. Order is shuffled with a
    fixed seed so a pull is reproducible.
    """
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(WORK, exist_ok=True)

    dates = [d.strip() for d in (args.dates or args.date).split(",") if d.strip()]
    per_day = {}
    for d in dates:
        per_day[d] = dataset_files(f"kaggle/kaggriculture-episodes-{d}")
        print(f"  {d}: {len(per_day[d])} episodes listed")

    rng = random.Random(args.seed)
    for d in dates:
        rng.shuffle(per_day[d])
    # Round-robin across days so a short run still spans all of them.
    order = []
    for i in range(max(len(v) for v in per_day.values())):
        for d in dates:
            if i < len(per_day[d]):
                order.append((d, per_day[d][i]))

    manifest = {}
    mpath = os.path.join(OUT, "manifest.json")
    if os.path.exists(mpath):
        with open(mpath) as f:
            manifest = json.load(f)
    team_count = Counter(v.get("team") for v in manifest.values())
    band_count = Counter(v.get("band") for v in manifest.values())
    band_quota = max(1, args.limit // max(len(BANDS), 1)) if args.bands else None

    made = skipped_team = skipped_band = 0
    for date, name in order:
        if made >= args.limit:
            break
        ep = int(name[:-5])
        if any(k.startswith(f"ghost-{ep}-") for k in manifest):
            continue
        path = _fetch(date, name)
        if not path:
            continue
        try:
            with open(path) as f:
                d = json.load(f)
            seed = (d.get("info") or {}).get("seed")
            teams = (d.get("info") or {}).get("TeamNames") or ["?", "?"]
            rew = d.get("rewards") or [0, 0]
            if seed is None:
                continue
            # Only the stronger side is worth keeping as an opponent.
            seat = 0 if (rew[0] or 0) >= (rew[1] or 0) else 1
            score = float(rew[seat] or 0)
            team = str(teams[seat])
            if team_count[team] >= args.per_team:
                skipped_team += 1
                continue
            band = _band(score)
            if band_quota and band_count[band] >= band_quota:
                skipped_band += 1
                continue
            # `steps[i]["action"]` produced `steps[i]["observation"]`, so an
            # agent asked at step i must return `_TURNS[i + 1]`. Off by one, the
            # plan runs a turn late against the previous turn's board and the
            # replay silently produces a *different* plausible season -- which is
            # why `verify` used to report 114% of the original score and that was
            # read as success. Verified: +1 reproduces a real episode to the
            # dollar and to the shop sequence; +0 does not.
            turns = [s[seat].get("action") for s in d["steps"][1:]]
            blob = base64.b64encode(
                gzip.compress(json.dumps(turns).encode(), 9)).decode()
            fn = f"ghost-{ep}-{seat}.py"
            with open(os.path.join(OUT, fn), "w") as f:
                f.write(TEMPLATE.format(team=teams[seat], ep=ep, seat=seat,
                                        score=float(rew[seat] or 0),
                                        seed=int(seed), blob=blob))
            manifest[fn[:-3]] = {"episode": ep, "seat": seat, "seed": int(seed),
                                 "team": team, "date": date, "band": band,
                                 "original_score": score,
                                 "opponent_score": float(rew[1 - seat] or 0)}
            team_count[team] += 1
            band_count[band] += 1
            made += 1
            # Written every time, not once at the end: a run that is interrupted
            # -- and these run for an hour -- otherwise leaves orphan .py files
            # with no manifest entry, which `tournament.py ghosts` then cannot
            # seed correctly.
            with open(mpath, "w") as mf:
                json.dump(manifest, mf, indent=1, sort_keys=True)
            print(f"  {fn}  {teams[seat][:22]:22s} ${float(rew[seat] or 0):>9,.0f}  "
                  f"seed {seed}  ({os.path.getsize(os.path.join(OUT, fn))/1024:.0f} KB)")
        except Exception as e:
            print(f"  {ep}: {type(e).__name__}: {e}")
        finally:
            if os.path.exists(path):
                os.remove(path)

    with open(mpath, "w") as f:
        json.dump(manifest, f, indent=1, sort_keys=True)
    print(f"\n{made} ghosts written to {OUT}/ ({len(manifest)} total)")
    if skipped_team or skipped_band:
        print(f"  discarded after download: {skipped_team} over the per-team cap, "
              f"{skipped_band} over a score-band quota")
    return 0


def cmd_verify(args):
    """How much of its original score does a ghost still reach against us?

    A ghost is open-loop and the weed RNG is shared, so it cannot reproduce its
    game exactly. If it reaches most of its score it is a strong, honest
    opponent; if it collapses, it is noise wearing a good player's name.
    """
    from kaggle_environments import make
    import statistics as st
    with open(os.path.join(OUT, "manifest.json")) as f:
        manifest = json.load(f)
    names = sorted(manifest)[:args.limit]
    ratios = []
    print(f"{'ghost':22s} {'original':>10s} {'replayed':>10s} {'kept':>6s}  opponent")
    for n in names:
        m = manifest[n]
        env = make("kaggriculture", configuration={"seed": m["seed"]})
        left = os.path.join(OUT, n + ".py")
        pair = [left, args.against] if m["seat"] == 0 else [args.against, left]
        env.run(pair)
        got = float(env.steps[-1][m["seat"]]["reward"] or 0)
        opp = float(env.steps[-1][1 - m["seat"]]["reward"] or 0)
        r = got / max(m["original_score"], 1)
        ratios.append(r)
        print(f"{n:22s} {m['original_score']:>10,.0f} {got:>10,.0f} {r:>6.0%}  "
              f"{opp:>9,.0f}")
    if ratios:
        print(f"\nkept a median of {st.median(ratios):.0%} of the original score "
              f"over {len(ratios)} ghosts")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("make")
    p.add_argument("--date", default=None, help="one day, e.g. 2026-08-09")
    p.add_argument("--dates", default=None,
                   help="comma-separated days, sampled round-robin")
    p.add_argument("--limit", type=int, default=20)
    p.add_argument("--per-team", type=int, default=3,
                   help="cap on ghosts from one team (default 3)")
    p.add_argument("--bands", action="store_true",
                   help="fill score bands evenly instead of taking any score")
    p.add_argument("--seed", type=int, default=17, help="shuffle seed")
    p.set_defaults(fn=cmd_make)
    b = sub.add_parser("balance")
    b.set_defaults(fn=cmd_balance)
    v = sub.add_parser("verify")
    v.add_argument("--limit", type=int, default=8)
    v.add_argument("--against",
                   default="agents/final4/smallhold-crew-mgtightgrain-flood-blind-compost-shopwise.py")
    v.set_defaults(fn=cmd_verify)
    args = ap.parse_args()
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
