#!/usr/bin/env python
"""Turn a top-of-the-leaderboard trajectory into a local opponent.

The echo chamber problem, stated plainly: every agent in `agents/lib` shares one
execution path, so a tournament between them measures which *configuration* of
that path is best and can never measure the path itself. `agents/spar/` was an
attempt to escape it by fitting atom configurations to real opponents' digests,
and it does not: a fitted configuration still runs on our engine, which works
21-27% of its actions where the top of the ladder works 40.6%.

A **ghost** does not fit anything. It replays the recorded action sequence of a
3,100-rated player, turn by turn, exactly as that player issued it.

    python tools/ghost.py make --date 2026-08-09 --limit 20
    python tools/ghost.py verify --limit 8

The seed matters. `configuration.seed` is scrubbed from the replay so agents
cannot read it, but `info.seed` survives, and replaying on that seed gives the
ghost the same starting board it actually played. `tools/tournament.py` is told
the seed through the manifest.

**What a ghost is not.** It is open-loop: it cannot react to us. Its farm work is
largely independent of what we do, but its market timing is stale, and the weed
RNG is shared between both farms and scales with each one's empty tiles — so our
different play perturbs its board too. `verify` measures exactly how much of its
original score a ghost still reaches, and refuses to ship one that collapses.
"""

import argparse
import base64
import gzip
import json
import os
import subprocess
import sys
import zipfile

OUT = "agents/ghosts"
WORK = "data/topeps"

TEMPLATE = '''"""Ghost of {team} — episode {ep}, seat {seat}, original score ${score:,.0f}.

Not a strategy. The recorded action sequence of a player rated ~3,100, replayed
turn by turn. Generated by tools/ghost.py; do not edit.

Open-loop: it cannot react. Replay on seed {seed} to give it the board it played.
"""

import base64
import gzip
import json

_SEED = {seed}
_TURNS = json.loads(gzip.decompress(base64.b64decode(
    "{blob}"
)).decode())
_PASS = {{"farmer": ["PASS"], "hands": [], "market": []}}


def agent(obs):
    try:
        i = int(obs.get("step", 0) or 0)
        a = _TURNS[i] if 0 <= i < len(_TURNS) else None
        return a if a else _PASS
    except Exception:
        return _PASS
'''


def _fetch(date, name):
    slug = f"kaggle/kaggriculture-episodes-{date}"
    path = os.path.join(WORK, name)
    subprocess.run(["kaggle", "datasets", "download", slug, "-f", name,
                    "-p", WORK, "--force"], capture_output=True, timeout=900)
    if not os.path.exists(path) and os.path.exists(path + ".zip"):
        with zipfile.ZipFile(path + ".zip") as z:
            z.extractall(WORK)
        os.remove(path + ".zip")
    return path if os.path.exists(path) else None


def cmd_make(args):
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(WORK, exist_ok=True)
    slug = f"kaggle/kaggriculture-episodes-{args.date}"
    out, token = [], None
    while True:
        cmd = ["kaggle", "datasets", "files", slug, "--page-size", "200"]
        if token:
            cmd += ["--page-token", token]
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=300).stdout
        token = None
        for line in r.splitlines():
            if line.startswith("Next Page Token = "):
                token = line.split(" = ", 1)[1].strip()
                continue
            p = line.split()
            if p and p[0].endswith(".json"):
                out.append(p[0])
        if not token:
            break

    manifest = {}
    mpath = os.path.join(OUT, "manifest.json")
    if os.path.exists(mpath):
        with open(mpath) as f:
            manifest = json.load(f)

    made = 0
    for name in out:
        if made >= args.limit:
            break
        ep = int(name[:-5])
        if any(k.startswith(f"ghost-{ep}-") for k in manifest):
            continue
        path = _fetch(args.date, name)
        if not path:
            continue
        try:
            with open(path) as f:
                d = json.load(f)
            seed = (d.get("info") or {}).get("seed")
            teams = (d.get("info") or {}).get("TeamNames") or ["?", "?"]
            rew = d.get("rewards") or [0, 0]
            if seed is None:
                continue
            # Only the stronger side is worth keeping as an opponent.
            seat = 0 if (rew[0] or 0) >= (rew[1] or 0) else 1
            turns = [s[seat].get("action") for s in d["steps"]]
            blob = base64.b64encode(
                gzip.compress(json.dumps(turns).encode(), 9)).decode()
            fn = f"ghost-{ep}-{seat}.py"
            with open(os.path.join(OUT, fn), "w") as f:
                f.write(TEMPLATE.format(team=teams[seat], ep=ep, seat=seat,
                                        score=float(rew[seat] or 0),
                                        seed=int(seed), blob=blob))
            manifest[fn[:-3]] = {"episode": ep, "seat": seat, "seed": int(seed),
                                 "team": teams[seat],
                                 "original_score": float(rew[seat] or 0),
                                 "opponent_score": float(rew[1 - seat] or 0)}
            made += 1
            print(f"  {fn}  {teams[seat][:22]:22s} ${float(rew[seat] or 0):>9,.0f}  "
                  f"seed {seed}  ({os.path.getsize(os.path.join(OUT, fn))/1024:.0f} KB)")
        except Exception as e:
            print(f"  {ep}: {type(e).__name__}: {e}")
        finally:
            if os.path.exists(path):
                os.remove(path)

    with open(mpath, "w") as f:
        json.dump(manifest, f, indent=1, sort_keys=True)
    print(f"\n{made} ghosts written to {OUT}/ ({len(manifest)} total)")
    return 0


def cmd_verify(args):
    """How much of its original score does a ghost still reach against us?

    A ghost is open-loop and the weed RNG is shared, so it cannot reproduce its
    game exactly. If it reaches most of its score it is a strong, honest
    opponent; if it collapses, it is noise wearing a good player's name.
    """
    from kaggle_environments import make
    import statistics as st
    with open(os.path.join(OUT, "manifest.json")) as f:
        manifest = json.load(f)
    names = sorted(manifest)[:args.limit]
    ratios = []
    print(f"{'ghost':22s} {'original':>10s} {'replayed':>10s} {'kept':>6s}  opponent")
    for n in names:
        m = manifest[n]
        env = make("kaggriculture", configuration={"seed": m["seed"]})
        left = os.path.join(OUT, n + ".py")
        pair = [left, args.against] if m["seat"] == 0 else [args.against, left]
        env.run(pair)
        got = float(env.steps[-1][m["seat"]]["reward"] or 0)
        opp = float(env.steps[-1][1 - m["seat"]]["reward"] or 0)
        r = got / max(m["original_score"], 1)
        ratios.append(r)
        print(f"{n:22s} {m['original_score']:>10,.0f} {got:>10,.0f} {r:>6.0%}  "
              f"{opp:>9,.0f}")
    if ratios:
        print(f"\nkept a median of {st.median(ratios):.0%} of the original score "
              f"over {len(ratios)} ghosts")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("make")
    p.add_argument("--date", required=True)
    p.add_argument("--limit", type=int, default=20)
    p.set_defaults(fn=cmd_make)
    v = sub.add_parser("verify")
    v.add_argument("--limit", type=int, default=8)
    v.add_argument("--against",
                   default="agents/final4/smallhold-crew-mgtightgrain-flood-blind-compost-shopwise.py")
    v.set_defaults(fn=cmd_verify)
    args = ap.parse_args()
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
