#!/usr/bin/env python
"""Render the strategy leaderboard from data/arena.sqlite.

Emits a markdown table into the repo and a self-contained HTML page suitable for
publishing, so collaborators can see which strategies are winning without
running anything themselves. Re-run after every tournament; the same file paths
are overwritten, so a published page keeps its URL.

    python tools/leaderboard.py --run latest
    python tools/leaderboard.py --run latest --html site/leaderboard.html
"""

import argparse
import html
import json
import os
import statistics
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import db as DB  # noqa: E402

AXES = ["land", "labour", "produce", "market", "intel", "muck"]


def load(con, run_id):
    ratings = [dict(r) for r in con.execute(
        "SELECT * FROM ratings WHERE run_id=? ORDER BY bt_elo DESC", (run_id,))]
    atoms = {}
    for r in con.execute("SELECT name, atoms, alias FROM agents"):
        try:
            atoms[r["name"]] = (json.loads(r["atoms"] or "{}"), r["alias"])
        except Exception:
            atoms[r["name"]] = ({}, None)
    run = dict(con.execute("SELECT * FROM runs WHERE id=?", (run_id,)).fetchone())
    return run, ratings, atoms


def atom_effects(ratings, atoms):
    """Mean BT-Elo per atom option -- the main effect of each choice."""
    buckets = defaultdict(lambda: defaultdict(list))
    for r in ratings:
        a, _ = atoms.get(r["agent"], ({}, None))
        for ax in AXES:
            if ax in a:
                buckets[ax][a[ax]].append(r["bt_elo"])
    out = {}
    for ax, opts in buckets.items():
        rows = [(opt, statistics.mean(v), len(v)) for opt, v in opts.items() if v]
        rows.sort(key=lambda t: -t[1])
        out[ax] = rows
    return out


def render_md(run, ratings, atoms, effects, top=40):
    L = []
    L.append("# Strategy leaderboard\n")
    L.append(f"Run **#{run['id']}** · `{run['label']}` · {run['kind']} · "
             f"{run['n_agents']:,} strategies · {run['n_episodes']:,} episodes · "
             f"{run['seeds']} seeds/pair · finished {run['finished_at']}\n")
    L.append("Ranked by **Bradley-Terry** strength — the same estimator Kaggle uses "
             "for the final leaderboard. BT-Elo is relative to the median strategy "
             "in the field; +400 means 10:1 odds.\n")
    L.append("> A high win rate with a low median $ means the strategy wins by "
             "denying the shared market rather than by earning. That does score on "
             "the ladder, but it is fragile against opponents who do not feed it.\n")

    L.append(f"## Top {top}\n")
    L.append("| # | BT-Elo | win% | median $ | sd $ | strategy | alias |")
    L.append("|--:|-------:|-----:|---------:|-----:|----------|-------|")
    for i, r in enumerate(ratings[:top], 1):
        _, alias = atoms.get(r["agent"], ({}, None))
        L.append(f"| {i} | {r['bt_elo']:+.0f} | {r['winrate']*100:.0f} | "
                 f"{r['median_money']:,.0f} | {r['sd_money']:,.0f} | "
                 f"`{r['agent']}` | {alias or ''} |")

    L.append("\n## Atom main effects\n")
    L.append("Mean BT-Elo of every strategy carrying each option. This is the "
             "marginal value of the choice, averaged over everything else.\n")
    for ax in AXES:
        if ax not in effects:
            continue
        L.append(f"**{ax}**\n")
        L.append("| option | mean BT-Elo | strategies |")
        L.append("|--------|------------:|-----------:|")
        for opt, mean, n in effects[ax]:
            L.append(f"| `{opt}` | {mean:+.0f} | {n} |")
        L.append("")

    L.append("## Bottom 10\n")
    L.append("| BT-Elo | win% | median $ | strategy |")
    L.append("|-------:|-----:|---------:|----------|")
    for r in ratings[-10:]:
        L.append(f"| {r['bt_elo']:+.0f} | {r['winrate']*100:.0f} | "
                 f"{r['median_money']:,.0f} | `{r['agent']}` |")
    L.append("\n---\n*Generated by `tools/leaderboard.py` from `data/arena.sqlite`.*")
    return "\n".join(L)


AXIS_ORDER = ["land", "labour", "produce", "market", "intel", "muck"]

CSS = """
/* Palette: an agronomy field-trial record. Cool green-biased neutrals, deep
   chlorophyll accent, ochre for caution, brick for negative. Light is the
   base; dark redefines only tokens, guarded for all three viewer states. */
:root{
  --ground:#f7f8f5; --surface:#ffffff; --raise:#f1f3ee;
  --ink:#171a16; --mute:#6a7266; --faint:#98a094;
  --rule:#dfe3da; --hair:#eceee8;
  --accent:#2f6b4f; --accent-soft:#dce9e0;
  --warn:#9a6b1f; --crit:#8c3a2e;
  --bar:#c3dbcb; --bar-neg:#e3cdc8;
}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){
  --ground:#101310; --surface:#181c17; --raise:#1e231d;
  --ink:#e6e9e2; --mute:#8d968a; --faint:#6c756a;
  --rule:#2a302a; --hair:#212620;
  --accent:#7fbf95; --accent-soft:#22332a;
  --warn:#d0a45e; --crit:#d08573;
  --bar:#2c4433; --bar-neg:#432e2a;
}}
:root[data-theme="dark"]{
  --ground:#101310; --surface:#181c17; --raise:#1e231d;
  --ink:#e6e9e2; --mute:#8d968a; --faint:#6c756a;
  --rule:#2a302a; --hair:#212620;
  --accent:#7fbf95; --accent-soft:#22332a;
  --warn:#d0a45e; --crit:#d08573;
  --bar:#2c4433; --bar-neg:#432e2a;
}

*{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{
  margin:0; padding:2.5rem 1.5rem 5rem;
  background:var(--ground); color:var(--ink);
  font:15px/1.55 ui-sans-serif,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  font-variant-numeric:tabular-nums;
}
.wrap{max-width:1180px;margin:0 auto;display:flex;flex-direction:column;gap:2.5rem}

header{display:flex;flex-direction:column;gap:.55rem}
.eyebrow{
  font:600 11px/1 ui-monospace,SFMono-Regular,"SF Mono",Menlo,Consolas,monospace;
  letter-spacing:.16em;text-transform:uppercase;color:var(--accent);
}
h1{margin:0;font-size:2rem;font-weight:650;letter-spacing:-.025em;text-wrap:balance}
.sub{margin:0;color:var(--mute);max-width:66ch}

.facts{
  display:flex;flex-wrap:wrap;gap:0 2rem;padding-top:.6rem;
  border-top:1px solid var(--rule);
  font:12px/1.9 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:var(--mute);
}
.facts b{color:var(--ink);font-weight:600}

.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:1px;
  background:var(--rule);border:1px solid var(--rule);border-radius:3px;overflow:hidden}
.stat{background:var(--surface);padding:.85rem 1rem}
.stat .k{font:600 10.5px/1 ui-monospace,Menlo,monospace;letter-spacing:.13em;
  text-transform:uppercase;color:var(--faint)}
.stat .v{margin-top:.35rem;font-size:1.4rem;font-weight:600;letter-spacing:-.02em}
.stat .v.sm{font-size:.95rem;font-weight:600;font-family:ui-monospace,Menlo,monospace;
  letter-spacing:0;line-height:1.3;word-break:break-all}

section{display:flex;flex-direction:column;gap:.85rem}
h2{margin:0;font-size:1.05rem;font-weight:650;letter-spacing:-.01em;
  padding-bottom:.45rem;border-bottom:2px solid var(--ink)}
h2 span{float:right;font:400 12px/1.6 ui-monospace,Menlo,monospace;color:var(--mute)}
.lede{margin:0;color:var(--mute);font-size:.9rem;max-width:70ch}

.note{
  background:var(--surface);border:1px solid var(--rule);
  border-left:3px solid var(--warn);border-radius:0 3px 3px 0;
  padding:.7rem .95rem;font-size:.875rem;color:var(--mute);max-width:78ch;
}
.note b{color:var(--ink)}

.scroll{overflow-x:auto;border:1px solid var(--rule);border-radius:3px;background:var(--surface)}
table{border-collapse:collapse;width:100%;font-size:.85rem;min-width:900px}
thead th{
  position:sticky;top:0;background:var(--raise);
  font:600 10.5px/1 ui-monospace,Menlo,monospace;letter-spacing:.1em;
  text-transform:uppercase;color:var(--faint);
  padding:.6rem .55rem;text-align:left;border-bottom:1px solid var(--rule);white-space:nowrap;
}
tbody td{padding:.36rem .55rem;border-bottom:1px solid var(--hair);white-space:nowrap;vertical-align:middle}
tbody tr:last-child td{border-bottom:0}
tbody tr:hover td{background:var(--raise)}
th.n,td.n{text-align:right}
td.rk{color:var(--faint);font:12px/1 ui-monospace,Menlo,monospace;width:2.6rem}
td.el{font:600 13px/1 ui-monospace,Menlo,monospace;width:5rem}
td.el.p{color:var(--accent)} td.el.m{color:var(--crit)}
td.num{font:12.5px/1 ui-monospace,Menlo,monospace}
td.dim{color:var(--mute)}

/* Elo magnitude bar, drawn behind the number */
.elo{position:relative;display:flex;justify-content:flex-end;align-items:center;
  padding:.28rem .4rem;border-radius:2px;overflow:hidden}
.elo i{position:absolute;left:0;top:0;bottom:0;background:var(--bar);border-radius:2px}
.elo.m i{background:var(--bar-neg)}
.elo span{position:relative}

/* The strategy "genome": six fixed slots, one per atom axis, so a reader can
   scan a column and see which option the leaders share. */
.gene{display:flex;gap:1px;font:11.5px/1 ui-monospace,SFMono-Regular,Menlo,monospace}
.gene b{
  display:block;padding:.34rem .45rem;background:var(--raise);color:var(--mute);
  font-weight:400;border-radius:2px;text-align:center;
}
.gene b.top{background:var(--accent-soft);color:var(--accent);font-weight:600}
.gene b:nth-child(1){min-width:6.6rem}
.gene b:nth-child(2){min-width:3.6rem}
.gene b:nth-child(3){min-width:6.2rem}
.gene b:nth-child(4){min-width:4.9rem}
.gene b:nth-child(5){min-width:4.9rem}
.gene b:nth-child(6){min-width:3.8rem}
.alias{margin-left:.5rem;color:var(--accent);font:600 11.5px/1 ui-monospace,Menlo,monospace}

.effects{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:1rem}
.axis{background:var(--surface);border:1px solid var(--rule);border-radius:3px;padding:.9rem 1rem 1rem}
.axis h3{margin:0 0 .1rem;font:600 10.5px/1 ui-monospace,Menlo,monospace;
  letter-spacing:.13em;text-transform:uppercase;color:var(--faint)}
.axis .cap{margin:0 0 .7rem;font-size:.8rem;color:var(--mute)}
.row{display:grid;grid-template-columns:7.4rem 1fr 5.4rem;align-items:center;gap:.5rem;
  height:1.6rem;font:12px/1 ui-monospace,Menlo,monospace}
.row .t{color:var(--ink);overflow:hidden;text-overflow:ellipsis}
.row .g{position:relative;height:.62rem;background:var(--hair);border-radius:1px}
.row .g i{position:absolute;left:0;top:0;bottom:0;background:var(--bar);border-radius:1px}
.row .g i.m{background:var(--bar-neg)}
.row .v{text-align:right;color:var(--mute)}

footer{padding-top:1.4rem;border-top:1px solid var(--rule);
  color:var(--faint);font-size:.8rem;max-width:74ch}
footer code{color:var(--mute)}
code{font:12.5px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
a{color:var(--accent)}
:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
@media (max-width:640px){
  body{padding:1.75rem 1rem 4rem}
  h1{font-size:1.55rem}
  .facts{gap:0 1.2rem}
}
"""

AXIS_CAPTION = {
    "land": "quadrants owned, of four",
    "labour": "hands hired per day",
    "produce": "what the farm makes",
    "market": "how sale size reacts to price",
    "intel": "use of the opponent's public board",
    "muck": "the free daily fertilizer",
}


def render_html(run, ratings, atoms, effects, top=40):
    def esc(s):
        return html.escape(str(s))

    best_opt = {ax: rows[0][0] for ax, rows in effects.items() if rows}

    def gene(agent):
        a, _ = atoms.get(agent, ({}, None))
        if not a:
            return f"<code>{esc(agent)}</code>"
        cells = []
        for ax in AXIS_ORDER:
            opt = a.get(ax, "")
            cls = " class='top'" if opt and opt == best_opt.get(ax) else ""
            cells.append(f"<b{cls}>{esc(opt)}</b>")
        return f"<div class='gene'>{''.join(cells)}</div>"

    hi = max((abs(r["bt_elo"]) for r in ratings), default=1.0) or 1.0
    body = []
    for i, r in enumerate(ratings[:top], 1):
        _, alias = atoms.get(r["agent"], ({}, None))
        neg = r["bt_elo"] < 0
        w = 4 + 96 * abs(r["bt_elo"]) / hi
        body.append(
            f"<tr><td class='rk'>{i}</td>"
            f"<td class='el {'m' if neg else 'p'}'><span class='elo{' m' if neg else ''}'>"
            f"<i style='width:{w:.1f}%'></i><span>{r['bt_elo']:+.0f}</span></span></td>"
            f"<td class='n num'>{r['winrate']*100:.0f}%</td>"
            f"<td class='n num'>{r['median_money']:,.0f}</td>"
            f"<td class='n num dim'>{r['sd_money']:,.0f}</td>"
            f"<td>{gene(r['agent'])}"
            + (f"<span class='alias'>{esc(alias)}</span>" if alias else "")
            + "</td></tr>")

    cards = []
    for ax in AXIS_ORDER:
        rows = effects.get(ax)
        if not rows:
            continue
        lo = min(v for _, v, _ in rows)
        hi_a = max(v for _, v, _ in rows)
        span = (hi_a - lo) or 1.0
        bars = []
        for opt, mean, n in rows:
            w = 3 + 97 * (mean - lo) / span
            bars.append(
                f"<div class='row'><span class='t'>{esc(opt)}</span>"
                f"<span class='g'><i class='{'m' if mean < 0 else ''}' "
                f"style='width:{w:.1f}%'></i></span>"
                f"<span class='v'>{mean:+.0f} · {n}</span></div>")
        cards.append(
            f"<div class='axis'><h3>{esc(ax)}</h3>"
            f"<p class='cap'>{esc(AXIS_CAPTION.get(ax,''))}</p>{''.join(bars)}</div>")

    tail = []
    for r in ratings[-10:]:
        tail.append(
            f"<tr><td class='el m'>{r['bt_elo']:+.0f}</td>"
            f"<td class='n num'>{r['winrate']*100:.0f}%</td>"
            f"<td class='n num'>{r['median_money']:,.0f}</td>"
            f"<td>{gene(r['agent'])}</td></tr>")

    lead = ratings[0]
    saturated = sum(1 for r in ratings if r["winrate"] >= 0.999)
    sat_note = ""
    if saturated > 1:
        sat_note = (f"<div class='note'><b>{saturated} strategies went undefeated.</b> "
                    "Bradley-Terry strength diverges on a perfect record, so those rows "
                    "share a clipped score and their order here is arbitrary. Separating "
                    "them needs a round robin among themselves, not a panel.</div>")

    return f"""<title>Kaggriculture strategy trial</title>
<style>{CSS}</style>
<div class="wrap">

<header>
  <div class="eyebrow">Kaggriculture &middot; variety trial</div>
  <h1>Strategy leaderboard</h1>
  <p class="sub">Every strategy is one option from each of six orthogonal atoms, so its
  name states exactly what it does. Ranked by Bradley-Terry strength &mdash; the estimator
  Kaggle uses for the final leaderboard.</p>
  <div class="facts">
    <span>run <b>#{run['id']}</b></span>
    <span>{esc(run['kind'])}</span>
    <span><b>{run['n_agents']:,}</b> strategies</span>
    <span><b>{run['n_episodes']:,}</b> episodes</span>
    <span><b>{run['seeds']}</b> seeds per pairing, both seats</span>
    <span>{esc(run['finished_at'])}</span>
  </div>
</header>

<div class="stats">
  <div class="stat"><div class="k">Strategies</div><div class="v">{run['n_agents']:,}</div></div>
  <div class="stat"><div class="k">Episodes</div><div class="v">{run['n_episodes']:,}</div></div>
  <div class="stat"><div class="k">Leader win rate</div><div class="v">{lead['winrate']*100:.0f}%</div></div>
  <div class="stat"><div class="k">Leader median $</div><div class="v">{lead['median_money']:,.0f}</div></div>
  <div class="stat"><div class="k">Leading strategy</div><div class="v sm">{esc(lead['agent'])}</div></div>
</div>

<section>
  <h2>Ranking<span>top {min(top, len(ratings))} of {len(ratings):,}</span></h2>
  <p class="lede">The six cells after each score are the strategy's atoms, always in the
  same order &mdash; land, labour, produce, market, intel, muck. Scan a column to see what
  the leaders have in common; highlighted cells are the best option on that axis by mean effect.</p>
  {sat_note}
  <div class="note">A high win rate beside a low median&nbsp;$ means the strategy wins by
  <b>denying the shared market</b> rather than by earning. That does score on a win/loss
  ladder, but it is fragile against opponents who do not feed it.</div>
  <div class="scroll"><table>
    <thead><tr><th>#</th><th>BT-Elo</th><th class="n">win</th><th class="n">median&nbsp;$</th>
    <th class="n">sd&nbsp;$</th><th>land &middot; labour &middot; produce &middot; market &middot; intel &middot; muck</th></tr></thead>
    <tbody>{''.join(body)}</tbody>
  </table></div>
</section>

<section>
  <h2>Atom main effects<span>mean BT-Elo &middot; n strategies</span></h2>
  <p class="lede">Mean score of every strategy carrying each option, averaged over all
  other axes &mdash; the marginal value of the choice itself. Options with a small n are
  measured on fewer strategies and should be read with more caution.</p>
  <div class="effects">{''.join(cards)}</div>
</section>

<section>
  <h2>Bottom ten<span>the floor of the space</span></h2>
  <div class="scroll"><table>
    <thead><tr><th>BT-Elo</th><th class="n">win</th><th class="n">median&nbsp;$</th>
    <th>land &middot; labour &middot; produce &middot; market &middot; intel &middot; muck</th></tr></thead>
    <tbody>{''.join(tail)}</tbody>
  </table></div>
</section>

<footer>
  Generated by <code>tools/leaderboard.py</code> from <code>data/arena.sqlite</code>, which
  holds every episode this project has run. Regenerate after each tournament to refresh
  this page. BT-Elo is relative to the median strategy in this field; +400 is 10:1 odds.
  The strategy space is non-transitive, so a ranking is always a ranking <em>against this
  field</em>.
</footer>

</div>"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default="latest")
    ap.add_argument("--top", type=int, default=40)
    ap.add_argument("--md", default="docs/LEADERBOARD.md")
    ap.add_argument("--html", default="site/leaderboard.html")
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)
    con = DB.connect()
    run = DB.latest_run(con) if args.run == "latest" else {"id": int(args.run)}
    if not run:
        raise SystemExit("no finished runs in the database")

    run, ratings, atoms = load(con, run["id"])
    if not ratings:
        raise SystemExit(f"run #{run['id']} has no ratings")
    effects = atom_effects(ratings, atoms)

    with open(args.md, "w") as f:
        f.write(render_md(run, ratings, atoms, effects, args.top))
    print(f"wrote {args.md}")
    os.makedirs(os.path.dirname(os.path.abspath(args.html)), exist_ok=True)
    with open(args.html, "w") as f:
        f.write(render_html(run, ratings, atoms, effects, args.top))
    print(f"wrote {args.html}")

    print(f"\nrun #{run['id']}: {run['n_agents']} strategies, {run['n_episodes']:,} episodes")
    for ax in AXES:
        if ax in effects:
            best = effects[ax][0]
            worst = effects[ax][-1]
            print(f"  {ax:8s} best {best[0]:12s} {best[1]:+7.0f}   "
                  f"worst {worst[0]:12s} {worst[1]:+7.0f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
