#!/usr/bin/env python
"""Stamp out the single-strategy probe agents from agents/probe.py.

Each probe commits to one mechanic and abandons the rest, so the league can
price that mechanic in isolation. Regenerate after editing agents/probe.py:

    python tools/make_probes.py
"""

import os
import re
import sys

SRC = "agents/probe.py"
OUT = "agents/probes"

# name -> (tunable overrides, one-line description)
PROBES = {
    # --- monoculture crops: what is each crop worth if it is all you do? ---
    "mono_wheat":      ({"CROP": '"WHEAT"', "ANIMAL": "None"}, "wheat only, no animals"),
    "mono_carrot":     ({"CROP": '"CARROT"', "ANIMAL": "None"}, "carrot only, no animals"),
    "mono_tomato":     ({"CROP": '"TOMATO"', "ANIMAL": "None"}, "tomato only, no animals"),
    "mono_strawberry": ({"CROP": '"STRAWBERRY"', "ANIMAL": "None"}, "strawberry only, no animals"),
    "mono_melon":      ({"CROP": '"MELON"', "ANIMAL": "None"}, "melon only, no animals"),

    # --- monoculture livestock: buy feed, farm no crops ---
    "mono_cow":   ({"CROP": "None", "ANIMAL": '"COW"'}, "cows only, feed bought from market"),
    "mono_sheep": ({"CROP": "None", "ANIMAL": '"SHEEP"'}, "sheep only, feed bought"),
    "mono_goose": ({"CROP": "None", "ANIMAL": '"GOOSE"'}, "geese only, feed bought"),

    # --- isolate the free fertilizer loop from the product loop ---
    "fert_only":    ({"CROP": "None", "ANIMAL": '"COW"', "HARVEST_PRODUCT": "False"},
                     "animals kept purely for the free daily fertilizer"),
    "product_only": ({"CROP": "None", "ANIMAL": '"COW"', "COLLECT_FERT": "False"},
                     "animals but fertilizer never collected"),

    # --- structural levers ---
    "one_quadrant":  ({"MAX_QUADRANTS": "1"}, "never buys land"),
    "two_quadrant":  ({"MAX_QUADRANTS": "2"}, "buys NE only"),
    "four_quadrant": ({"MAX_QUADRANTS": "4"}, "buys all land including SE"),

    # --- labour levers ---
    "no_hire":   ({"HAND_CAP": "0"}, "solo farmer, never hires"),
    "few_hands": ({"HAND_CAP": "4"}, "at most 4 hands"),
    "hire_max":  ({"HAND_CAP": "30", "HIRE_BUDGET_FRAC": "1.0"},
                  "hires until broke, ignores payroll cost"),

    # --- market levers ---
    "dump_all": ({"SELL_MODE": '"dump"'}, "sells everything immediately, no metering"),
    "hoarder":  ({"SELL_MODE": '"hoard"'}, "holds everything until the final liquidation"),

    # --- the probe's own mixed default, as a reference point ---
    "mixed_ref": ({}, "probe defaults: melon + cows, 3 quadrants, metered"),
}

HEADER = '''"""PROBE: {desc}

Generated by tools/make_probes.py from agents/probe.py -- do not edit directly.
Overrides: {ov}
"""
'''


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)
    with open(SRC) as f:
        src = f.read()
    os.makedirs(OUT, exist_ok=True)

    made = []
    for name, (ov, desc) in PROBES.items():
        text = src
        for k, v in ov.items():
            pat = re.compile(rf"^{re.escape(k)}\s*=\s*[^\n#]+", re.M)
            if not pat.search(text):
                raise SystemExit(f"tunable {k!r} not found in {SRC}")
            text = pat.sub(f"{k} = {v}    ", text, count=1)
        ov_s = ", ".join(f"{k}={v}" for k, v in ov.items()) or "(none)"
        text = HEADER.format(desc=desc, ov=ov_s) + text
        path = os.path.join(OUT, f"{name}.py")
        with open(path, "w") as f:
            f.write(text)
        made.append((name, desc, path))

    print(f"wrote {len(made)} probes to {OUT}/")
    for name, desc, _ in made:
        print(f"  {name:16s} {desc}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
